In [1]:
import pandas as pd

# Read only first 5 rows
train_s1 = pd.read_csv("train_source1.tsv", sep="\t", nrows=5)
train_s2 = pd.read_csv("train_source2.tsv", sep="\t", nrows=5)
train_s3 = pd.read_csv("train_source3.tsv", sep="\t", nrows=5)

test_s1 = pd.read_csv("test_source1.tsv", sep="\t", nrows=5)
test_s2 = pd.read_csv("test_source2.tsv", sep="\t", nrows=5)
test_s3 = pd.read_csv("test_source3.tsv", sep="\t", nrows=5)

gt = pd.read_csv("train_ground_truth.tsv", sep="\t", nrows=5)

print("TRAIN SOURCE 1")
display(train_s1)

print("TRAIN SOURCE 2")
display(train_s2)

print("TRAIN SOURCE 3")
display(train_s3)

print("TEST SOURCE 1")
display(test_s1)

print("TEST SOURCE 2")
display(test_s2)

print("TEST SOURCE 3")
display(test_s3)

print("GROUND TRUTH")
display(gt)

TRAIN SOURCE 1

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

TRAIN SOURCE 2

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

TRAIN SOURCE 3

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India

TEST SOURCE 1

,entity_id,business_name,business_address,country
0,S1-714132312,Zephay Labs Inc,"2621 Cotten Road, Tyler, TX",US
1,S1-106407869,Vision Partners Corp,"IA, Iowa City, 1064 Newton Rd, Unit 11",US
2,S1-156285671,<< Team Ecole,"175 Boulevard du Président Franklin Roosevelt,...",France
3,S1-689823050,Red Perfect Trading,"Mirzapur, Ews 12, Uttar Pradesh, Mirzapursadar...",India
4,S1-921369899,ZNB Club SARL,"Nouvelle-Aquitaine, La Teste-de-Buch, 5 bis Ru...",France

TEST SOURCE 2

,entity_id,business_name,business_address,country
0,S2-192345572,Brahma Infosoft,"COIMATORE COLONY, HUNSUR TQMYSORE DIST., Karna...",India
1,S2-566025912,Marina Ecole France Sarl,"63 R. DE DIEPPE, LILLE, Hauts-de-France",France
2,S2-158121477,SCI Ptit Àmicale,"18 RUE JEN ZAY, Dunkerque, Nord",France
3,S2-89663826,Apex Summit,"67 KENTUCKY ST, SALYERSVILLE, KY",US
4,S2-884102769,Fresh Truist,"8264 FILLY COURT, ROANOKE COUNTY, VA",US

TEST SOURCE 3

,entity_id,business_name,business_address,country
0,S3-462677478,मॉडर्न फाइनेंस,"No 10 Enkay Square, 448A, Udyog Vihar Phase V,...",India
1,S3-374810425,Shri Sai Infratech Co,"3/115, East Delhi, DL",India
2,S3-198586129,Fractales Amis Groupe S.A.S,"23 Rue Icmre, La Teste-de-buch, Gironde",France
3,S3-10300249,Shri Supreme Consulting Private (Limited),"H.no 910 A 3503, Mumbai, महाराष्ट्र",India
4,S3-604980231,Prime Realty Ventures Public Limited,"G.t. Karnal Road, Industrial Area, New Delhi, ...",India

GROUND TRUTH

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [2]:
# We already loaded only 5 rows earlier.
# Now load the smaller Source 1 and Ground Truth completely.

train_s1 = pd.read_csv("train_source1.tsv", sep="\t")
gt = pd.read_csv("train_ground_truth.tsv", sep="\t")

print("Train S1 shape:", train_s1.shape)
print("Ground Truth shape:", gt.shape)

print("\nTrain S1 countries:")
print(train_s1["country"].value_counts(dropna=False))

print("\nMissing values in S1:")
print(train_s1.isna().sum())

print("\nMissing values in Ground Truth:")
print(gt.isna().sum())

Train S1 shape: (2206821, 4)
Ground Truth shape: (2206821, 2)

Train S1 countries:
country
US       1323633
India     883188
Name: count, dtype: int64

Missing values in S1:
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

Missing values in Ground Truth:
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

In [3]:
print(train_s1.head())
print(gt.head())

      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [4]:
# Replace missing ground-truth values with empty strings
gt["matched_entity_ids"] = gt["matched_entity_ids"].fillna("")

# Number of matches for each S1
gt["num_matches"] = gt["matched_entity_ids"].apply(
    lambda x: 0 if x == "" else len(x.split(","))
)

print("Match count distribution:")
print(gt["num_matches"].value_counts().sort_index())

print("\nAverage matches per S1:")
print(gt["num_matches"].mean())

print("\nMaximum matches for one S1:")
print(gt["num_matches"].max())

print("\nNumber of S1 with 0 matches:")
print((gt["num_matches"] == 0).sum())

print("\nNumber of S1 with 1 match:")
print((gt["num_matches"] == 1).sum())

print("\nNumber of S1 with 2+ matches:")
print((gt["num_matches"] >= 2).sum())

Match count distribution:
num_matches
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

Average matches per S1:
3.4612526344456573

Maximum matches for one S1:
11

Number of S1 with 0 matches:
123247

Number of S1 with 1 match:
119157

Number of S1 with 2+ matches:
1964417

In [5]:
# See some examples with many matches
display(
    gt[gt["num_matches"] >= 3]
    [["source1_entity_id", "matched_entity_ids", "num_matches"]]
    .head(10)
)

,source1_entity_id,matched_entity_ids,num_matches
0,S1-965667,"S2-681193310,S2-743505751,S3-775321672,S3-1129...",5
1,S1-55344266,"S2-249013014,S2-197070651,S3-478195123,S3-3843...",4
2,S1-343815751,"S2-790675320,S2-479876582,S3-878454467",3
3,S1-656753428,"S2-153058913,S2-24659151,S3-679606215",3
4,S1-102811957,"S2-478959098,S2-553508714,S2-625774905,S3-7280...",6
5,S1-18727616,"S2-755677256,S3-187831601,S3-641489370,S3-4762...",4
9,S1-789009573,"S2-383871912,S3-74481402,S3-576451439",3
11,S1-7293388,"S2-7028416,S2-442723188,S2-157073701,S3-523120965",4
12,S1-546142636,"S2-487600131,S2-582477216,S2-392804085,S3-2000...",6
13,S1-274126313,"S2-736616474,S2-680265918,S2-51486805,S3-92563...",6

In [6]:
# Pick 5 S1 records that have matches
sample_gt = gt[gt["matched_entity_ids"] != ""].sample(5, random_state=42)

display(sample_gt[["source1_entity_id", "matched_entity_ids"]])

        source1_entity_id                                 matched_entity_ids
836854       S1-777210964  S2-12029274,S2-407524980,S3-970714334,S3-71292...
1105197      S1-190133982             S2-523219173,S3-716445195,S3-986804760
1626624      S1-970131671                          S2-670035601,S3-392756625
1911521      S1-391999301  S2-742819060,S2-339356009,S2-233734305,S3-9388...
1153974      S1-435988542                                       S2-500704398

In [7]:
# Show the corresponding S1 records
sample_s1 = train_s1[
    train_s1["entity_id"].isin(sample_gt["source1_entity_id"])
]

display(sample_s1)

,entity_id,business_name,business_address,country
65605,S1-391999301,Team Air Pvt. Ltd.,"Flat No:101, Anuska Towers, Opp. Mercedes Benz...",India
599807,S1-777210964,Davis Family Office,"88 Olive Circle, Lebanon, TN",US
891959,S1-970131671,3520 Main Road Realty Inc,"TX, 158 Simpson Lane, Somerset",US
917027,S1-435988542,Drayex Berto LLC,"Montgomery Village, MD, 19821 Wheelwright Drive",US
1639385,S1-190133982,MS Consultancy Corp,Shymala Appts 1St Floor Flat No. 4 Opp Ratna H...,India

In [8]:
try:
    import duckdb
    print("DuckDB is installed ✅")
    print("Version:", duckdb.__version__)
except ImportError:
    print("DuckDB is NOT installed ❌")

DuckDB is installed ✅
Version: 1.5.5

In [9]:
import re
import unicodedata

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Keep letters, marks, numbers and spaces
    result = []

    for ch in text:
        category = unicodedata.category(ch)

        if category[0] in {"L", "M", "N"} or ch.isspace():
            result.append(ch)
        else:
            result.append(" ")

    text = "".join(result)

    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text

In [10]:
# Read only 100,000 rows from S2 and S3
s2_sample = pd.read_csv(
    "train_source2.tsv",
    sep="\t",
    nrows=100000
)

s3_sample = pd.read_csv(
    "train_source3.tsv",
    sep="\t",
    nrows=100000
)

# Normalize name and address
s2_sample["name_norm"] = s2_sample["business_name"].apply(normalize_text)
s2_sample["address_norm"] = s2_sample["business_address"].apply(normalize_text)

s3_sample["name_norm"] = s3_sample["business_name"].apply(normalize_text)
s3_sample["address_norm"] = s3_sample["business_address"].apply(normalize_text)

print("S2 sample:", s2_sample.shape)
print("S3 sample:", s3_sample.shape)

print("\nS2 unique normalized names:")
print(s2_sample["name_norm"].nunique())

print("\nS3 unique normalized names:")
print(s3_sample["name_norm"].nunique())

print("\nSample S2:")
display(
    s2_sample[
        ["entity_id", "business_name", "name_norm",
         "business_address", "address_norm", "country"]
    ].head(10)
)

S2 sample: (100000, 6)
S3 sample: (100000, 6)

S2 unique normalized names:
97649

S3 unique normalized names:
97857

Sample S2:

,entity_id,business_name,name_norm,business_address,address_norm,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",kh no 570 13 new delhi west delhi delhi,India
1,S2-764573417,-- Holloway Peak Inc Seafood,holloway peak inc seafood,"105 ELM ST, MORGANTON, NC",105 elm st morganton nc,US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",g 3 571 gulmohar colony bhopal madhya pradesh,India
3,S2-163963287,Summit Inc,summit inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",greensboro nc 19 1 2 stardust trail,US
4,S2-49942811,Delta Tetlecommunication Inc,delta tetlecommunication inc,"914 PIERPONT AVE, CLEVELAND, OH",914 pierpont ave cleveland oh,US
5,S2-138046867,Lee and Lawson,lee and lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",1702 pine avenue city of menomonie wi,US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,shivshakti vidyalaya vidyalaya overseas corpor...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",h no 204 c road hoshiarpur punjab punjab,India
7,S2-277444929,Shree Infracon Private Ltd,shree infracon private ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",63 2275 7 alhind tower first floor jafferkhan ...,India
8,S2-721031885,Chavira Platinum Chimera LLC,chavira platinum chimera llc,"282 SAXONY DRIVE, FTT MITCHELL, KY",282 saxony drive ftt mitchell ky,US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,foundation excel agency private limited,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",hn 753 e 1 bharat nagar 104 1 1 erandwane maha...,India

In [11]:
# Let's look at the first ground-truth record
first_gt = gt.iloc[0]

print("S1 ID:")
print(first_gt["source1_entity_id"])

print("\nCorrect matching S2/S3 IDs:")
print(first_gt["matched_entity_ids"])

S1 ID:
S1-965667

Correct matching S2/S3 IDs:
S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364

In [12]:
s1_id = first_gt["source1_entity_id"]

s1_record = train_s1[train_s1["entity_id"] == s1_id]

display(s1_record)

,entity_id,business_name,business_address,country
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US

In [13]:
# Get the correct matching IDs
matched_ids = first_gt["matched_entity_ids"].split(",")

s2_ids = {x for x in matched_ids if x.startswith("S2-")}
s3_ids = {x for x in matched_ids if x.startswith("S3-")}

print("S2 IDs:", s2_ids)
print("S3 IDs:", s3_ids)

found_s2 = []
found_s3 = []

# Search S2 in chunks
for chunk in pd.read_csv(
    "train_source2.tsv",
    sep="\t",
    chunksize=100000,
    dtype=str
):
    rows = chunk[chunk["entity_id"].isin(s2_ids)]
    if len(rows) > 0:
        found_s2.append(rows)

    if sum(len(x) for x in found_s2) == len(s2_ids):
        break

# Search S3 in chunks
for chunk in pd.read_csv(
    "train_source3.tsv",
    sep="\t",
    chunksize=100000,
    dtype=str
):
    rows = chunk[chunk["entity_id"].isin(s3_ids)]
    if len(rows) > 0:
        found_s3.append(rows)

    if sum(len(x) for x in found_s3) == len(s3_ids):
        break

matched_s2 = pd.concat(found_s2, ignore_index=True)
matched_s3 = pd.concat(found_s3, ignore_index=True)

print("MATCHED S2 RECORDS")
display(matched_s2)

print("MATCHED S3 RECORDS")
display(matched_s3)

S2 IDs: {'S2-681193310', 'S2-743505751'}
S3 IDs: {'S3-860443364', 'S3-11291185', 'S3-775321672'}
MATCHED S2 RECORDS

      entity_id                 business_name business_address country
0  S2-681193310  Maure Wilblims Colombier Inc              NaN      US
1  S2-743505751      Maure Williams Colombier              NaN      US

MATCHED S3 RECORDS

,entity_id,business_name,business_address,country
0,S3-860443364,Maure Williams Inc Center,NaN,US
1,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
2,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [14]:
# Positive match IDs from ground truth
positive_ids = set(matched_s2["entity_id"]) | set(matched_s3["entity_id"])

# S1 information
s1_row = s1_record.iloc[0]

# -------------------------
# Positive pairs -> label 1
# -------------------------

positive_s2 = matched_s2.copy()
positive_s3 = matched_s3.copy()

positive_s2["s1_id"] = s1_row["entity_id"]
positive_s2["label"] = 1

positive_s3["s1_id"] = s1_row["entity_id"]
positive_s3["label"] = 1

# -------------------------
# Negative pairs -> label 0
# Take records from same country
# but which are NOT true matches
# -------------------------

negative_s2 = s2_sample[
    (s2_sample["country"] == s1_row["country"]) &
    (~s2_sample["entity_id"].isin(positive_ids))
].head(5).copy()

negative_s3 = s3_sample[
    (s3_sample["country"] == s1_row["country"]) &
    (~s3_sample["entity_id"].isin(positive_ids))
].head(5).copy()

negative_s2["s1_id"] = s1_row["entity_id"]
negative_s2["label"] = 0

negative_s3["s1_id"] = s1_row["entity_id"]
negative_s3["label"] = 0

# Combine everything
training_pairs = pd.concat(
    [positive_s2, positive_s3, negative_s2, negative_s3],
    ignore_index=True
)

print("Training pairs:")
display(
    training_pairs[
        ["s1_id", "entity_id", "business_name",
         "business_address", "country", "label"]
    ]
)

Training pairs:

,s1_id,entity_id,business_name,business_address,country,label
0,S1-965667,S2-681193310,Maure Wilblims Colombier Inc,NaN,US,1
1,S1-965667,S2-743505751,Maure Williams Colombier,NaN,US,1
2,S1-965667,S3-860443364,Maure Williams Inc Center,NaN,US,1
3,S1-965667,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US,1
4,S1-965667,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US,1
5,S1-965667,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US,0
6,S1-965667,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US,0
7,S1-965667,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US,0
8,S1-965667,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US,0
9,S1-965667,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US,0
10,S1-965667,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US,0
11,S1-965667,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US,0
12,S1-965667,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US,0
13,S1-965667,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US,0
14,S1-965667,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US,0

In [15]:
import re
import unicodedata
from difflib import SequenceMatcher

def normalize_text(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = unicodedata.normalize("NFKC", text)

    result = []

    for ch in text:
        category = unicodedata.category(ch)

        if category[0] in {"L", "M", "N"} or ch.isspace():
            result.append(ch)
        else:
            result.append(" ")

    text = "".join(result)
    text = re.sub(r"\s+", " ", text).strip()

    return text


# Recreate normalized columns
train_s1["name_norm"] = train_s1["business_name"].apply(normalize_text)
train_s1["address_norm"] = train_s1["business_address"].apply(normalize_text)

# Recreate our S1 record
s1_id = "S1-965667"
s1_record = train_s1[train_s1["entity_id"] == s1_id]

print("S1 record restored ✅")
display(s1_record)

S1 record restored ✅

,entity_id,business_name,business_address,country,name_norm,address_norm
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",US,maure williams colombier inc,85 wayne avenue ticonderoga ny

In [16]:
def similarity(a, b):
    return SequenceMatcher(None, str(a), str(b)).ratio()


s1_name = s1_record.iloc[0]["name_norm"]
s1_address = s1_record.iloc[0]["address_norm"]
s1_country = s1_record.iloc[0]["country"]

training_pairs["name_similarity"] = training_pairs["business_name"].apply(
    lambda x: similarity(s1_name, normalize_text(x))
)

training_pairs["address_similarity"] = training_pairs["business_address"].apply(
    lambda x: similarity(s1_address, normalize_text(x))
)

training_pairs["country_same"] = (
    training_pairs["country"] == s1_country
).astype(int)

display(
    training_pairs[
        [
            "s1_id",
            "entity_id",
            "label",
            "name_similarity",
            "address_similarity",
            "country_same"
        ]
    ]
)

,s1_id,entity_id,label,name_similarity,address_similarity,country_same
0,S1-965667,S2-681193310,1,0.964286,0.000000,1
1,S1-965667,S2-743505751,1,0.923077,0.000000,1
2,S1-965667,S3-860443364,1,0.679245,0.000000,1
3,S1-965667,S3-775321672,1,0.171429,0.763158,1
4,S1-965667,S3-11291185,1,0.888889,0.685714,1
5,S1-965667,S2-764573417,0,0.339623,0.339623,1
6,S1-965667,S2-163963287,0,0.315789,0.215385,1
7,S1-965667,S2-49942811,0,0.357143,0.338983,1
8,S1-965667,S2-138046867,0,0.285714,0.477612,1
9,S1-965667,S2-721031885,0,0.214286,0.290323,1
10,S1-965667,S3-202863386,0,0.347826,0.254545,1
11,S1-965667,S3-22467283,0,0.254545,0.237288,1
12,S1-965667,S3-671162755,0,0.380952,0.366197,1
13,S1-965667,S3-578159284,0,0.344828,0.265060,1
14,S1-965667,S3-121412624,0,0.245614,0.278481,1

In [17]:
!pip install rapidfuzz catboost scikit-learn -q

In [18]:
import re
from collections import defaultdict

def name_block_key(name):
    name = normalize_text(name)
    # spaces hatao
    name = re.sub(r"\s+", "", name)
    # first 12 characters
    return name[:12]

def address_number(address):
    if pd.isna(address):
        return ""
    
    nums = re.findall(r"\d+", str(address))
    
    if nums:
        return nums[0]
    
    return ""


# Create blocking keys
s2_sample["name_block"] = s2_sample["business_name"].apply(name_block_key)
s3_sample["name_block"] = s3_sample["business_name"].apply(name_block_key)

s2_sample["address_number"] = s2_sample["business_address"].apply(address_number)
s3_sample["address_number"] = s3_sample["business_address"].apply(address_number)

print("Blocking keys created ✅")

Blocking keys created ✅

In [19]:
# Name index
name_index = defaultdict(list)

for entity_id, country, key in zip(
    s2_sample["entity_id"],
    s2_sample["country"],
    s2_sample["name_block"]
):
    if key:
        name_index[(country, key)].append(entity_id)

for entity_id, country, key in zip(
    s3_sample["entity_id"],
    s3_sample["country"],
    s3_sample["name_block"]
):
    if key:
        name_index[(country, key)].append(entity_id)


# Address-number index
address_index = defaultdict(list)

for entity_id, country, key in zip(
    s2_sample["entity_id"],
    s2_sample["country"],
    s2_sample["address_number"]
):
    if key:
        address_index[(country, key)].append(entity_id)

for entity_id, country, key in zip(
    s3_sample["entity_id"],
    s3_sample["country"],
    s3_sample["address_number"]
):
    if key:
        address_index[(country, key)].append(entity_id)

print("Indexes created ✅")

Indexes created ✅

In [20]:
# Our example S1
row = s1_record.iloc[0]

country = row["country"]
name_key = name_block_key(row["business_name"])
number_key = address_number(row["business_address"])

candidates = set()

# Block 1: name
candidates.update(
    name_index.get((country, name_key), [])
)

# Block 2: address number
candidates.update(
    address_index.get((country, number_key), [])
)

print("S1:", row["entity_id"])
print("Name block:", name_key)
print("Address number:", number_key)

print("\nNumber of candidates:", len(candidates))
print("\nCandidates:")
print(candidates)

S1: S1-965667
Name block: maurewilliam
Address number: 85

Number of candidates: 88

Candidates:
{'S2-381972947', 'S2-472071324', 'S3-351565477', 'S2-186137676', 'S3-483169021', 'S2-810670202', 'S2-634402709', 'S3-25597362', 'S3-300343466', 'S2-972017821', 'S3-944060825', 'S3-470080574', 'S3-681303979', 'S3-202927718', 'S2-39379741', 'S3-536074232', 'S2-242319689', 'S2-154297166', 'S3-264527141', 'S2-979910605', 'S3-386495516', 'S3-990750207', 'S3-851445372', 'S2-562400582', 'S3-128523734', 'S2-869942991', 'S2-569492456', 'S2-649356417', 'S3-100697074', 'S2-214120696', 'S3-38985587', 'S2-419994533', 'S3-761079443', 'S2-983459191', 'S3-716783948', 'S3-546162643', 'S2-385956436', 'S2-820954601', 'S3-619279944', 'S2-402326574', 'S3-812434061', 'S3-720537586', 'S3-471340724', 'S2-798982674', 'S2-932854937', 'S3-365214598', 'S2-274815545', 'S3-239828372', 'S3-440123202', 'S3-250017761', 'S2-388253121', 'S2-348738746', 'S3-181139659', 'S2-599375147', 'S3-287838768', 'S2-381231365', 'S3-902868661', 'S3-259598575', 'S3-37529341', 'S3-894921460', 'S2-808728262', 'S2-827996366', 'S3-332442906', 'S3-456879367', 'S3-777791054', 'S3-486010851', 'S3-939492839', 'S3-317041213', 'S2-291380996', 'S3-397415525', 'S2-934909510', 'S3-860443364', 'S2-641139196', 'S2-469753503', 'S3-469809881', 'S2-570158332', 'S2-72530234', 'S2-133252993', 'S2-331481433', 'S3-510420433', 'S2-952350839', 'S3-125075828', 'S2-843805065', 'S3-484710471', 'S3-708899441', 'S2-886900265', 'S3-313163368', 'S2-494986322'}

In [21]:
true_matches = set(matched_ids)

found = true_matches.intersection(candidates)
missed = true_matches - candidates

print("True matches:", true_matches)
print("\nFound by blocking:", found)
print("\nMissed by blocking:", missed)

print("\nBlocking recall:",
      len(found) / len(true_matches))

True matches: {'S3-775321672', 'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-860443364'}

Found by blocking: {'S3-860443364'}

Missed by blocking: {'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-775321672'}

Blocking recall: 0.2

In [22]:
def get_name_tokens(name):
    name = normalize_text(name)
    tokens = name.split()

    # Very short/common tokens ignore
    tokens = [t for t in tokens if len(t) >= 3]

    return tokens


# Create token-prefix index for S2 and S3
token_index = defaultdict(list)

for entity_id, country, name in zip(
    s2_sample["entity_id"],
    s2_sample["country"],
    s2_sample["business_name"]
):
    tokens = get_name_tokens(name)

    for token in set(tokens):
        key = (country, token[:5])
        token_index[key].append(entity_id)


for entity_id, country, name in zip(
    s3_sample["entity_id"],
    s3_sample["country"],
    s3_sample["business_name"]
):
    tokens = get_name_tokens(name)

    for token in set(tokens):
        key = (country, token[:5])
        token_index[key].append(entity_id)


# Get candidates for our S1
row = s1_record.iloc[0]

s1_tokens = get_name_tokens(row["business_name"])

token_candidates = set()

for token in s1_tokens:
    key = (row["country"], token[:5])
    token_candidates.update(token_index.get(key, []))


print("S1:", row["entity_id"])
print("S1 tokens:", s1_tokens)
print("Number of token-block candidates:", len(token_candidates))

print("\nTrue matches found:")
print(true_matches.intersection(token_candidates))

print("\nMissed true matches:")
print(true_matches - token_candidates)

print("\nToken blocking recall:")
print(
    len(true_matches.intersection(token_candidates))
    / len(true_matches)
)

S1: S1-965667
S1 tokens: ['maure', 'williams', 'colombier', 'inc']
Number of token-block candidates: 16204

True matches found:
{'S3-860443364'}

Missed true matches:
{'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-775321672'}

Token blocking recall:
0.2

In [23]:
print("True matches present in S2 sample:")

for x in true_matches:
    if x.startswith("S2-"):
        print(x, x in set(s2_sample["entity_id"]))

print("\nTrue matches present in S3 sample:")

for x in true_matches:
    if x.startswith("S3-"):
        print(x, x in set(s3_sample["entity_id"]))

True matches present in S2 sample:
S2-681193310 False
S2-743505751 False

True matches present in S3 sample:
S3-775321672 False
S3-11291185 False
S3-860443364 True

In [24]:
target_ids = true_matches

found_records = []

for file in ["train_source2.tsv", "train_source3.tsv"]:

    print("Searching:", file)

    for chunk in pd.read_csv(
        file,
        sep="\t",
        chunksize=100000,
        dtype=str
    ):
        found = chunk[chunk["entity_id"].isin(target_ids)]

        if not found.empty:
            found_records.append(found)

        # If all 5 are found, we can stop
        found_ids = set(
            pd.concat(found_records)["entity_id"]
        ) if found_records else set()

        if target_ids.issubset(found_ids):
            break

all_true_records = pd.concat(found_records, ignore_index=True)

display(
    all_true_records[
        ["entity_id", "business_name", "business_address", "country"]
    ]
)

Searching: train_source2.tsv
Searching: train_source3.tsv

,entity_id,business_name,business_address,country
0,S2-681193310,Maure Wilblims Colombier Inc,NaN,US
1,S2-743505751,Maure Williams Colombier,NaN,US
2,S3-860443364,Maure Williams Inc Center,NaN,US
3,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",US
4,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",US

In [25]:
from rapidfuzz import fuzz
import re

s1 = s1_record.iloc[0]

def get_numbers(text):
    if pd.isna(text):
        return set()
    return set(re.findall(r"\d+", str(text)))


s1_name = normalize_text(s1["business_name"])
s1_address = normalize_text(s1["business_address"])
s1_numbers = get_numbers(s1["business_address"])

results = []

for _, row in all_true_records.iterrows():

    candidate_name = normalize_text(row["business_name"])
    candidate_address = normalize_text(row["business_address"])

    name_score = fuzz.token_set_ratio(
        s1_name,
        candidate_name
    ) / 100

    address_score = fuzz.token_set_ratio(
        s1_address,
        candidate_address
    ) / 100

    candidate_numbers = get_numbers(row["business_address"])

    if len(s1_numbers | candidate_numbers) == 0:
        number_overlap = 0
    else:
        number_overlap = len(s1_numbers & candidate_numbers) / len(
            s1_numbers | candidate_numbers
        )

    country_same = int(
        s1["country"] == row["country"]
    )

    results.append({
        "entity_id": row["entity_id"],
        "business_name": row["business_name"],
        "name_score": round(name_score, 3),
        "address_score": round(address_score, 3),
        "number_overlap": round(number_overlap, 3),
        "country_same": country_same
    })

signal_table = pd.DataFrame(results)

display(signal_table)

,entity_id,business_name,name_score,address_score,number_overlap,country_same
0,S2-681193310,Maure Wilblims Colombier Inc,0.964,0.000,0.0,1
1,S2-743505751,Maure Williams Colombier,1.000,0.000,0.0,1
2,S3-860443364,Maure Williams Inc Center,0.837,0.000,0.0,1
3,S3-775321672,Dréxkor,0.114,0.824,1.0,1
4,S3-11291185,maurewilliamscolombier.com,0.630,0.743,0.0,1

In [26]:
rule_candidates = signal_table[
    (signal_table["name_score"] >= 0.80) |
    (signal_table["address_score"] >= 0.70) |
    (signal_table["number_overlap"] > 0)
]

print("Candidates captured by rule:")
display(rule_candidates)

print("True matches captured:",
      len(rule_candidates))

print("Total true matches:",
      len(signal_table))

print("Recall:",
      len(rule_candidates) / len(signal_table))

Candidates captured by rule:

,entity_id,business_name,name_score,address_score,number_overlap,country_same
0,S2-681193310,Maure Wilblims Colombier Inc,0.964,0.000,0.0,1
1,S2-743505751,Maure Williams Colombier,1.000,0.000,0.0,1
2,S3-860443364,Maure Williams Inc Center,0.837,0.000,0.0,1
3,S3-775321672,Dréxkor,0.114,0.824,1.0,1
4,S3-11291185,maurewilliamscolombier.com,0.630,0.743,0.0,1

True matches captured: 5
Total true matches: 5
Recall: 1.0

In [27]:
# Apply our improved blocking rule to the sample

s2_name_score = s2_sample["business_name"].apply(
    lambda x: fuzz.token_set_ratio(
        s1_name,
        normalize_text(x)
    ) / 100
)

s2_address_score = s2_sample["business_address"].apply(
    lambda x: fuzz.token_set_ratio(
        s1_address,
        normalize_text(x)
    ) / 100
)

s3_name_score = s3_sample["business_name"].apply(
    lambda x: fuzz.token_set_ratio(
        s1_name,
        normalize_text(x)
    ) / 100
)

s3_address_score = s3_sample["business_address"].apply(
    lambda x: fuzz.token_set_ratio(
        s1_address,
        normalize_text(x)
    ) / 100
)


# IMPORTANT: each comparison has its own brackets
s2_candidate_mask = (
    (s2_sample["country"] == s1["country"]) &
    (
        (s2_name_score >= 0.80) |
        (s2_address_score >= 0.70)
    )
)

s3_candidate_mask = (
    (s3_sample["country"] == s1["country"]) &
    (
        (s3_name_score >= 0.80) |
        (s3_address_score >= 0.70)
    )
)


sample_candidates = set(
    s2_sample.loc[s2_candidate_mask, "entity_id"]
).union(
    set(s3_sample.loc[s3_candidate_mask, "entity_id"])
)

print("Number of candidates:", len(sample_candidates))

print("\nTrue matches found:")
print(true_matches.intersection(sample_candidates))

print("\nNumber of true matches found:",
      len(true_matches.intersection(sample_candidates)))

Number of candidates: 12

True matches found:
{'S3-860443364'}

Number of true matches found: 1

In [28]:
# Inspect the blocking keys of the 5 true matches

check = all_true_records.copy()

check["name_norm"] = check["business_name"].apply(normalize_text)
check["address_norm"] = check["business_address"].apply(normalize_text)

check["name_block"] = check["business_name"].apply(name_block_key)

check["address_number"] = check["business_address"].apply(address_number)

display(
    check[
        [
            "entity_id",
            "business_name",
            "business_address",
            "name_block",
            "address_number"
        ]
    ]
)

,entity_id,business_name,business_address,name_block,address_number
0,S2-681193310,Maure Wilblims Colombier Inc,NaN,maurewilblim,
1,S2-743505751,Maure Williams Colombier,NaN,maurewilliam,
2,S3-860443364,Maure Williams Inc Center,NaN,maurewilliam,
3,S3-775321672,Dréxkor,"85 Wanye Avenue, Ticonderoga Townshiip, New York",dréxkor,85
4,S3-11291185,maurewilliamscolombier.com,"Wayne Ave, Ticonderoga Townshiip, New York",maurewilliam,

In [29]:
def token_prefixes(name):
    tokens = normalize_text(name).split()
    return [t[:5] for t in tokens if len(t) >= 3]


s1_tokens = token_prefixes(s1["business_name"])

print("S1:", s1["business_name"])
print("Token prefixes:", s1_tokens)

print("\nTrue-match token prefixes:")

for _, row in all_true_records.iterrows():
    print(row["entity_id"], "->", token_prefixes(row["business_name"]))

S1: Maure Williams Colombier Inc
Token prefixes: ['maure', 'willi', 'colom', 'inc']

True-match token prefixes:
S2-681193310 -> ['maure', 'wilbl', 'colom', 'inc']
S2-743505751 -> ['maure', 'willi', 'colom']
S3-860443364 -> ['maure', 'willi', 'inc', 'cente']
S3-775321672 -> ['dréxk']
S3-11291185 -> ['maure', 'com']

In [30]:
from collections import Counter

token_counts = Counter()

for name in s2_sample["business_name"]:
    for token in set(token_prefixes(name)):
        token_counts[token] += 1

for name in s3_sample["business_name"]:
    for token in set(token_prefixes(name)):
        token_counts[token] += 1

for token in s1_tokens:
    print(token, "->", token_counts[token], "records")

maure -> 23 records
willi -> 472 records
colom -> 40 records
inc -> 15748 records

In [31]:
# Keep only informative name tokens
MAX_TOKEN_FREQ = 1000

# Build a filtered token index
filtered_token_index = defaultdict(list)

for entity_id, country, name in zip(
    s2_sample["entity_id"],
    s2_sample["country"],
    s2_sample["business_name"]
):
    for token in set(token_prefixes(name)):
        if token_counts[token] <= MAX_TOKEN_FREQ:
            filtered_token_index[(country, token)].append(entity_id)

for entity_id, country, name in zip(
    s3_sample["entity_id"],
    s3_sample["country"],
    s3_sample["business_name"]
):
    for token in set(token_prefixes(name)):
        if token_counts[token] <= MAX_TOKEN_FREQ:
            filtered_token_index[(country, token)].append(entity_id)


# Generate candidates for our S1
rare_token_candidates = set()

for token in s1_tokens:
    if token_counts[token] <= MAX_TOKEN_FREQ:
        rare_token_candidates.update(
            filtered_token_index.get(
                (s1["country"], token),
                []
            )
        )

print("S1:", s1["entity_id"])
print("Useful tokens:", [
    t for t in s1_tokens
    if token_counts[t] <= MAX_TOKEN_FREQ
])

print("\nCandidates from rare-token blocking:",
      len(rare_token_candidates))

print("\nTrue matches found:")
print(true_matches.intersection(rare_token_candidates))

print("\nTrue matches found:",
      len(true_matches.intersection(rare_token_candidates)),
      "out of", len(true_matches))

S1: S1-965667
Useful tokens: ['maure', 'willi', 'colom']

Candidates from rare-token blocking: 531

True matches found:
{'S3-860443364'}

True matches found: 1 out of 5

In [32]:
def token_prefixes_4(name):
    tokens = normalize_text(name).split()
    return [t[:4] for t in tokens if len(t) >= 3]


# S1 ke useful 4-character prefixes
s1_4_prefixes = set()

for token in get_name_tokens(s1["business_name"]):
    prefix = token[:4]
    
    # inc jaise common token ko ignore
    if token_counts.get(token[:5], 0) <= 1000:
        s1_4_prefixes.add(prefix)

print("S1 4-character prefixes:")
print(s1_4_prefixes)

print("\nTrue match 4-character prefixes:")

for _, row in all_true_records.iterrows():
    print(
        row["entity_id"],
        "->",
        token_prefixes_4(row["business_name"])
    )

S1 4-character prefixes:
{'colo', 'will', 'maur'}

True match 4-character prefixes:
S2-681193310 -> ['maur', 'wilb', 'colo', 'inc']
S2-743505751 -> ['maur', 'will', 'colo']
S3-860443364 -> ['maur', 'will', 'inc', 'cent']
S3-775321672 -> ['dréx']
S3-11291185 -> ['maur', 'com']

In [33]:
def four_char_tokens(name):
    tokens = normalize_text(name).split()
    return {t[:4] for t in tokens if len(t) >= 3}


s1_tokens4 = four_char_tokens(s1["business_name"])
s1_numbers = get_numbers(s1["business_address"])

print("S1 4-char tokens:", s1_tokens4)
print("S1 address numbers:", s1_numbers)

print("\nChecking 5 true matches:\n")

for _, row in all_true_records.iterrows():

    candidate_tokens = four_char_tokens(row["business_name"])
    candidate_numbers = get_numbers(row["business_address"])

    token_hit = bool(s1_tokens4 & candidate_tokens)
    number_hit = bool(s1_numbers & candidate_numbers)

    captured = token_hit or number_hit

    print(
        row["entity_id"],
        "| name hit:", token_hit,
        "| number hit:", number_hit,
        "| captured:", captured
    )

S1 4-char tokens: {'colo', 'inc', 'will', 'maur'}
S1 address numbers: {'85'}

Checking 5 true matches:

S2-681193310 | name hit: True | number hit: False | captured: True
S2-743505751 | name hit: True | number hit: False | captured: True
S3-860443364 | name hit: True | number hit: False | captured: True
S3-775321672 | name hit: False | number hit: True | captured: True
S3-11291185 | name hit: True | number hit: False | captured: True

In [34]:
import re
import pandas as pd

# Our S1
row = s1_record.iloc[0]

country = row["country"]

# From our earlier experiment:
name_prefixes = {"maur", "will", "colo"}
address_number = "85"

# Regex for any useful 4-character name prefix
name_pattern = r"(?<!\w)(?:maur|will|colo)"

# Regex for address number 85
number_pattern = r"(?<!\d)85(?!\d)"

all_candidates_full = set()

for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("\nScanning:", filename)

    rows_found = 0

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        # Only same-country records
        chunk = chunk[
            chunk["country"].eq(country)
        ].copy()

        if chunk.empty:
            continue

        # Lightweight normalization for this US example
        name = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        address = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        # Blocking condition
        name_hit = name.str.contains(
            name_pattern,
            regex=True,
            na=False
        )

        number_hit = address.str.contains(
            number_pattern,
            regex=True,
            na=False
        )

        candidates = chunk[name_hit | number_hit]

        all_candidates_full.update(
            candidates["entity_id"].tolist()
        )

        rows_found += len(candidates)

        if rows_found % 10000 == 0 and rows_found > 0:
            print("Candidates found so far:", rows_found)

print("\n==============================")
print("FULL DATA BLOCKING RESULT")
print("==============================")

print("Total candidates:", len(all_candidates_full))

print("\nTrue matches found:")
print(true_matches.intersection(all_candidates_full))

print("\nTrue matches missed:")
print(true_matches - all_candidates_full)

print(
    "\nTrue matches captured:",
    len(true_matches.intersection(all_candidates_full)),
    "out of",
    len(true_matches)
)

Scanning: train_source2.tsv

Scanning: train_source3.tsv

==============================
FULL DATA BLOCKING RESULT
==============================
Total candidates: 68590

True matches found:
{'S3-775321672', 'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-860443364'}

True matches missed:
set()

True matches captured: 5 out of 5

In [35]:
name_only_candidates = set()
address_only_candidates = set()

# Same full S2/S3 scan, but only count the reason
for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Checking:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        chunk = chunk[chunk["country"] == country]

        if chunk.empty:
            continue

        name = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
        )

        address = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
        )

        name_hit = name.str.contains(
            r"(?<!\w)(?:maur|will|colo)",
            regex=True,
            na=False
        )

        address_hit = address.str.contains(
            r"(?<!\d)85(?!\d)",
            regex=True,
            na=False
        )

        name_only_candidates.update(
            chunk.loc[name_hit, "entity_id"]
        )

        address_only_candidates.update(
            chunk.loc[address_hit, "entity_id"]
        )

print("\nName-block candidates:", len(name_only_candidates))
print("Address-number candidates:", len(address_only_candidates))
print(
    "Combined candidates:",
    len(name_only_candidates | address_only_candidates)
)

Checking: train_source2.tsv
Checking: train_source3.tsv

Name-block candidates: 62391
Address-number candidates: 6265
Combined candidates: 68590

In [36]:
name_only_candidates = set()
address_only_candidates = set()

# Same full S2/S3 scan, but only count the reason
for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Checking:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        chunk = chunk[chunk["country"] == country]

        if chunk.empty:
            continue

        name = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
        )

        address = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
        )

        name_hit = name.str.contains(
            r"(?<!\w)(?:maur|will|colo)",
            regex=True,
            na=False
        )

        address_hit = address.str.contains(
            r"(?<!\d)85(?!\d)",
            regex=True,
            na=False
        )

        name_only_candidates.update(
            chunk.loc[name_hit, "entity_id"]
        )

        address_only_candidates.update(
            chunk.loc[address_hit, "entity_id"]
        )

print("\nName-block candidates:", len(name_only_candidates))
print("Address-number candidates:", len(address_only_candidates))
print(
    "Combined candidates:",
    len(name_only_candidates | address_only_candidates)
)

Checking: train_source2.tsv
Checking: train_source3.tsv

Name-block candidates: 62391
Address-number candidates: 6265
Combined candidates: 68590

In [37]:
# SMARTER BLOCKING TEST
# We are still testing only S1-965667

s1 = s1_record.iloc[0]

all_smart_candidates = set()

for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Scanning:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        # Same country only
        chunk = chunk[chunk["country"] == s1["country"]].copy()

        if chunk.empty:
            continue

        # Normalize
        names = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        addresses = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        # --------------------------------
        # NAME BLOCK
        # --------------------------------

        maur_hit = names.str.contains(
            r"(?<!\w)maur",
            regex=True,
            na=False
        )

        will_hit = names.str.contains(
            r"(?<!\w)will",
            regex=True,
            na=False
        )

        colo_hit = names.str.contains(
            r"(?<!\w)colo",
            regex=True,
            na=False
        )

        # Count how many useful name tokens matched
        name_hit_count = (
            maur_hit.astype(int)
            + will_hit.astype(int)
            + colo_hit.astype(int)
        )

        two_name_hits = name_hit_count >= 2

        # --------------------------------
        # ADDRESS BLOCK
        # --------------------------------

        number_hit = addresses.str.contains(
            r"(?<!\d)85(?!\d)",
            regex=True,
            na=False
        )

        address_token_hit = addresses.str.contains(
            r"(?<!\w)(?:wayn|tico)",
            regex=True,
            na=False
        )

        # --------------------------------
        # FINAL BLOCKING RULE
        # --------------------------------

        mask = (
            two_name_hits
            | number_hit
            | address_token_hit
        )

        candidates = chunk.loc[mask, "entity_id"]

        all_smart_candidates.update(candidates.tolist())


print("\n==============================")
print("SMART BLOCKING RESULT")
print("==============================")

print("Total candidates:", len(all_smart_candidates))

found = true_matches.intersection(all_smart_candidates)
missed = true_matches - all_smart_candidates

print("\nTrue matches found:")
print(found)

print("\nTrue matches missed:")
print(missed)

print(
    "\nTrue matches captured:",
    len(found),
    "out of",
    len(true_matches)
)

print(
    "\nRecall:",
    len(found) / len(true_matches)
)

Scanning: train_source2.tsv
Scanning: train_source3.tsv

==============================
SMART BLOCKING RESULT
==============================
Total candidates: 20816

True matches found:
{'S3-775321672', 'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-860443364'}

True matches missed:
set()

True matches captured: 5 out of 5

Recall: 1.0

In [38]:
# Breakdown of the 20,816 candidates

two_name_count = 0
number_count = 0
address_token_count = 0

combined_ids = set()

for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Checking:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        chunk = chunk[chunk["country"] == s1["country"]].copy()

        if chunk.empty:
            continue

        names = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        addresses = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        # Name signals
        maur_hit = names.str.contains(r"(?<!\w)maur", regex=True, na=False)
        will_hit = names.str.contains(r"(?<!\w)will", regex=True, na=False)
        colo_hit = names.str.contains(r"(?<!\w)colo", regex=True, na=False)

        name_hit_count = (
            maur_hit.astype(int)
            + will_hit.astype(int)
            + colo_hit.astype(int)
        )

        two_name_hits = name_hit_count >= 2

        # Address signals
        number_hit = addresses.str.contains(
            r"(?<!\d)85(?!\d)",
            regex=True,
            na=False
        )

        address_token_hit = addresses.str.contains(
            r"(?<!\w)(?:wayn|tico)",
            regex=True,
            na=False
        )

        # Counts
        two_name_count += two_name_hits.sum()
        number_count += number_hit.sum()
        address_token_count += address_token_hit.sum()

        # Combined candidates
        mask = (
            two_name_hits
            | number_hit
            | address_token_hit
        )

        combined_ids.update(
            chunk.loc[mask, "entity_id"].tolist()
        )

print("\n========================")
print("BLOCKING BREAKDOWN")
print("========================")

print("2+ name token records:", two_name_count)
print("Address-number records:", number_count)
print("Address-token records:", address_token_count)
print("Final unique candidates:", len(combined_ids))

print("\nTrue matches captured:",
      len(true_matches.intersection(combined_ids)),
      "out of",
      len(true_matches))

Checking: train_source2.tsv
Checking: train_source3.tsv

========================
BLOCKING BREAKDOWN
========================
2+ name token records: 90
Address-number records: 6265
Address-token records: 14471
Final unique candidates: 20816

True matches captured: 5 out of 5

In [39]:
# Check how many records contain each address token
# across the FULL training S2 + S3 files.

address_tokens_to_check = ["wayn", "tico"]

token_counts_address = {
    token: 0 for token in address_tokens_to_check
}

for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Checking:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=["business_address", "country"]
    ):

        chunk = chunk[chunk["country"] == s1["country"]]

        addresses = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        for token in address_tokens_to_check:
            token_counts_address[token] += addresses.str.contains(
                rf"(?<!\w){token}",
                regex=True,
                na=False
            ).sum()

print("\nAddress token frequencies:")

for token, count in token_counts_address.items():
    print(token, "->", count)

Checking: train_source2.tsv
Checking: train_source3.tsv

Address token frequencies:
wayn -> 14201
tico -> 277

In [40]:
# Test: remove common "wayn", keep selective "tico"

smart2_candidates = set()

for filename in ["train_source2.tsv", "train_source3.tsv"]:

    print("Scanning:", filename)

    for chunk in pd.read_csv(
        filename,
        sep="\t",
        chunksize=100000,
        dtype=str,
        usecols=[
            "entity_id",
            "business_name",
            "business_address",
            "country"
        ]
    ):

        chunk = chunk[chunk["country"] == s1["country"]].copy()

        if chunk.empty:
            continue

        names = (
            chunk["business_name"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        addresses = (
            chunk["business_address"]
            .fillna("")
            .str.lower()
            .str.replace(r"[^\w\s]", " ", regex=True)
            .str.replace(r"\s+", " ", regex=True)
            .str.strip()
        )

        # Two or more useful name tokens
        maur_hit = names.str.contains(r"(?<!\w)maur", regex=True, na=False)
        will_hit = names.str.contains(r"(?<!\w)will", regex=True, na=False)
        colo_hit = names.str.contains(r"(?<!\w)colo", regex=True, na=False)

        name_count = (
            maur_hit.astype(int)
            + will_hit.astype(int)
            + colo_hit.astype(int)
        )

        name_hit = name_count >= 2

        # Address number
        number_hit = addresses.str.contains(
            r"(?<!\d)85(?!\d)",
            regex=True,
            na=False
        )

        # Only selective address token
        tico_hit = addresses.str.contains(
            r"(?<!\w)tico",
            regex=True,
            na=False
        )

        mask = name_hit | number_hit | tico_hit

        smart2_candidates.update(
            chunk.loc[mask, "entity_id"].tolist()
        )

print("\n==============================")
print("SMART BLOCKING V2")
print("==============================")

print("Total candidates:", len(smart2_candidates))

found = true_matches.intersection(smart2_candidates)

print("True matches found:", found)
print("True matches captured:", len(found), "out of", len(true_matches))

Scanning: train_source2.tsv
Scanning: train_source3.tsv

==============================
SMART BLOCKING V2
==============================
Total candidates: 6625
True matches found: {'S3-775321672', 'S3-11291185', 'S2-681193310', 'S2-743505751', 'S3-860443364'}
True matches captured: 5 out of 5

In [41]:
# Select 100 random S1s for a blocking experiment

sample_100_s1 = train_s1.sample(
    100,
    random_state=42
)

print("Number of S1 records:", len(sample_100_s1))
display(
    sample_100_s1[
        ["entity_id", "business_name", "business_address", "country"]
    ].head(10)
)

Number of S1 records: 100

,entity_id,business_name,business_address,country
2195840,S1-53356671,Pediatric Medicine PLLC,"4850 20, Otisco, NY",US
1487051,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",US
1878277,S1-938947364,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US
993966,S1-195839862,Construction Ideaz Papers Private Limited,"Building No.4/606, Prabhul Cottage Karimbalur,...",India
565428,S1-655046555,Penaloza and Bittle First Inc.,"4255 Charleswood Avenue, Memphis, TN",US
1645753,S1-758070915,National Investments LLC,"1641 Virginia Lane, Hueytown, AL",US
1165724,S1-169338169,Reus Idaho Company,"Sanford, ME, 31 Guillemette Street",US
363842,S1-796421498,Creative Projects Limited,"12Thfloor, C, 1204, Roya Oasis, Jankalyan Naga...",India
962445,S1-802535179,Goar Stone LLC,"2105 Wood Ridge Cove, Cedar Park, TX",US
964820,S1-97176033,Lakshmi Consultants Private Limited,"A-301, New Sai Dham Chsl, Ramdev Park Road, Th...",India

In [42]:
# Ground truth for our 100 selected S1 records

sample_100_ids = set(sample_100_s1["entity_id"])

gt_100 = gt[
    gt["source1_entity_id"].isin(sample_100_ids)
].copy()

gt_100["matched_entity_ids"] = gt_100["matched_entity_ids"].fillna("")

print("Selected S1:", len(sample_100_ids))
print("Ground-truth rows found:", len(gt_100))

# Number of true matches for each selected S1
gt_100["num_matches"] = gt_100["matched_entity_ids"].apply(
    lambda x: 0 if x == "" else len(x.split(","))
)

print("\nMatch distribution:")
print(gt_100["num_matches"].value_counts().sort_index())

display(
    gt_100[
        ["source1_entity_id", "matched_entity_ids", "num_matches"]
    ].head(10)
)

Selected S1: 100
Ground-truth rows found: 100

Match distribution:
num_matches
0     12
1      3
2     17
3     18
4     25
5     18
6      4
7      1
8      1
10     1
Name: count, dtype: int64

,source1_entity_id,matched_entity_ids,num_matches
21045,S1-983540069,"S2-859028958,S2-4190133,S3-435171628,S3-189255...",6
28113,S1-541260963,,0
48581,S1-949002960,,0
52823,S1-207329319,"S2-938952817,S2-696233561,S2-653613388,S3-3581...",5
55100,S1-175111461,"S2-429308620,S2-883484447,S2-838267419,S3-4733...",4
86397,S1-169338169,"S2-626887099,S2-851548432,S2-519047819,S3-3453...",5
106644,S1-128350097,"S2-522197637,S2-928954639,S2-121897499,S2-2684...",7
117058,S1-843179540,"S2-474099966,S2-991925876,S2-437941242,S3-4119...",5
137155,S1-892236833,"S2-371079433,S2-736348556,S3-433939171,S3-7982...",4
163620,S1-938947364,"S2-159830603,S3-544960509,S3-268060208",3

In [43]:
from itertools import combinations
import re

# Common legal suffixes:
# These are not removed from the original data.
# They are only avoided as primary blocking keys.
LEGAL_SUFFIXES = {
    "inc", "incorporated",
    "ltd", "limited",
    "llc",
    "corp", "corporation",
    "co", "company",
    "pvt", "private",
    "public", "plc"
}


def get_name_prefixes(name):
    name = normalize_text(name)
    tokens = name.split()

    prefixes = set()

    for token in tokens:
        if len(token) >= 4 and token not in LEGAL_SUFFIXES:
            prefixes.add(token[:4])

    return sorted(prefixes)


def get_address_prefixes(address):
    address = normalize_text(address)
    tokens = address.split()

    prefixes = set()

    for token in tokens:
        if len(token) >= 4:
            prefixes.add(token[:4])

    return sorted(prefixes)


def get_numbers(address):
    if pd.isna(address):
        return []

    return re.findall(r"\d+", str(address))


# Create automatic blocking keys for every S1
sample_100_s1["name_prefixes"] = sample_100_s1["business_name"].apply(
    get_name_prefixes
)

sample_100_s1["name_pairs"] = sample_100_s1["name_prefixes"].apply(
    lambda x: list(combinations(x, 2))
)

sample_100_s1["address_prefixes"] = sample_100_s1["business_address"].apply(
    get_address_prefixes
)

sample_100_s1["address_numbers"] = sample_100_s1["business_address"].apply(
    get_numbers
)


display(
    sample_100_s1[
        [
            "entity_id",
            "business_name",
            "name_prefixes",
            "name_pairs",
            "address_numbers",
            "address_prefixes"
        ]
    ].head(10)
)

,entity_id,business_name,name_prefixes,name_pairs,address_numbers,address_prefixes
2195840,S1-53356671,Pediatric Medicine PLLC,"[medi, pedi, pllc]","[(medi, pedi), (medi, pllc), (pedi, pllc)]","[4850, 20]","[4850, otis]"
1487051,S1-320151505,Fetech National Twin,"[fete, nati, twin]","[(fete, nati), (fete, twin), (nati, twin)]",[19034],"[1903, road, wood]"
1878277,S1-938947364,General Design Innovations LLC,"[desi, gene, inno]","[(desi, gene), (desi, inno), (gene, inno)]",[7241],"[7241, aven, mesa, osag]"
993966,S1-195839862,Construction Ideaz Papers Private Limited,"[cons, idea, pape]","[(cons, idea), (cons, pape), (idea, pape)]","[4, 606]","[ayir, buil, cott, elak, kari, kera, prab, thi..."
565428,S1-655046555,Penaloza and Bittle First Inc.,"[bitt, firs, pena]","[(bitt, firs), (bitt, pena), (firs, pena)]",[4255],"[4255, aven, char, memp]"
1645753,S1-758070915,National Investments LLC,"[inve, nati]","[(inve, nati)]",[1641],"[1641, huey, lane, virg]"
1165724,S1-169338169,Reus Idaho Company,"[idah, reus]","[(idah, reus)]",[31],"[guil, sanf, stre]"
363842,S1-796421498,Creative Projects Limited,"[crea, proj]","[(crea, proj)]","[12, 1204]","[1204, 12th, bill, city, jank, maha, mala, mum..."
962445,S1-802535179,Goar Stone LLC,"[goar, ston]","[(goar, ston)]",[2105],"[2105, ceda, cove, park, ridg, wood]"
964820,S1-97176033,Lakshmi Consultants Private Limited,"[cons, laks]","[(cons, laks)]",[301],"[chsl, dham, maha, park, ramd, road, than]"

In [44]:
LEGAL_SUFFIXES = {
    "inc", "incorporated",
    "ltd", "limited",
    "llc",
    "pllc",
    "corp", "corporation",
    "co", "company",
    "pvt", "private",
    "public", "plc"
}

# Recreate the name prefixes after the correction
sample_100_s1["name_prefixes"] = sample_100_s1["business_name"].apply(
    get_name_prefixes
)

sample_100_s1["name_pairs"] = sample_100_s1["name_prefixes"].apply(
    lambda x: list(combinations(x, 2))
)

display(
    sample_100_s1[
        ["entity_id", "business_name", "name_prefixes", "name_pairs"]
    ].head(10)
)

,entity_id,business_name,name_prefixes,name_pairs
2195840,S1-53356671,Pediatric Medicine PLLC,"[medi, pedi]","[(medi, pedi)]"
1487051,S1-320151505,Fetech National Twin,"[fete, nati, twin]","[(fete, nati), (fete, twin), (nati, twin)]"
1878277,S1-938947364,General Design Innovations LLC,"[desi, gene, inno]","[(desi, gene), (desi, inno), (gene, inno)]"
993966,S1-195839862,Construction Ideaz Papers Private Limited,"[cons, idea, pape]","[(cons, idea), (cons, pape), (idea, pape)]"
565428,S1-655046555,Penaloza and Bittle First Inc.,"[bitt, firs, pena]","[(bitt, firs), (bitt, pena), (firs, pena)]"
1645753,S1-758070915,National Investments LLC,"[inve, nati]","[(inve, nati)]"
1165724,S1-169338169,Reus Idaho Company,"[idah, reus]","[(idah, reus)]"
363842,S1-796421498,Creative Projects Limited,"[crea, proj]","[(crea, proj)]"
962445,S1-802535179,Goar Stone LLC,"[goar, ston]","[(goar, ston)]"
964820,S1-97176033,Lakshmi Consultants Private Limited,"[cons, laks]","[(cons, laks)]"

In [45]:
# Quick summary of blocking keys for our 100 S1 records

total_name_pairs = sample_100_s1["name_pairs"].apply(len).sum()
total_name_prefixes = sample_100_s1["name_prefixes"].apply(len).sum()
total_address_numbers = sample_100_s1["address_numbers"].apply(len).sum()
total_address_prefixes = sample_100_s1["address_prefixes"].apply(len).sum()

print("100 S1 summary")
print("---------------------------")
print("Total name prefixes:", total_name_prefixes)
print("Total name pairs:", total_name_pairs)
print("Total address numbers:", total_address_numbers)
print("Total address prefixes:", total_address_prefixes)

print("\nExample:")
row = sample_100_s1.iloc[0]

print("S1:", row["entity_id"])
print("Name:", row["business_name"])
print("Name prefixes:", row["name_prefixes"])
print("Name pairs:", row["name_pairs"])
print("Address numbers:", row["address_numbers"])
print("Address prefixes:", row["address_prefixes"])

100 S1 summary
---------------------------
Total name prefixes: 226
Total name pairs: 173
Total address numbers: 168
Total address prefixes: 562

Example:
S1: S1-53356671
Name: Pediatric Medicine PLLC
Name prefixes: ['medi', 'pedi']
Name pairs: [('medi', 'pedi')]
Address numbers: ['4850', '20']
Address prefixes: ['4850', 'otis']

In [46]:
from collections import defaultdict
from itertools import combinations

# -----------------------------------------
# 1. Build lookup maps from our 100 S1s
# -----------------------------------------

name_pair_to_s1 = defaultdict(set)
address_pair_to_s1 = defaultdict(set)

# Also keep exact normalized names as an additional block
exact_name_to_s1 = defaultdict(set)

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    # ----- Name pair keys -----
    prefixes = set(row["name_prefixes"])

    for pair in combinations(sorted(prefixes), 2):
        name_pair_to_s1[(country, pair)].add(s1_id)

    # ----- Exact normalized name -----
    exact_name = normalize_text(row["business_name"])

    if exact_name:
        exact_name_to_s1[(country, exact_name)].add(s1_id)

    # ----- Address pair keys -----
    numbers = set(row["address_numbers"])
    addr_prefixes = set(row["address_prefixes"])

    for number in numbers:
        for prefix in addr_prefixes:
            address_pair_to_s1[(country, number, prefix)].add(s1_id)


print("Blocking lookup created ✅")
print("Name-pair keys:", len(name_pair_to_s1))
print("Exact-name keys:", len(exact_name_to_s1))
print("Address keys:", len(address_pair_to_s1))

Blocking lookup created ✅
Name-pair keys: 173
Exact-name keys: 100
Address keys: 970

In [47]:
import sys

!{sys.executable} -m pip install duckdb -q

In [48]:
import duckdb

print("DuckDB installed ✅")
print("Version:", duckdb.__version__)

DuckDB installed ✅
Version: 1.5.5

In [49]:
import duckdb

con = duckdb.connect()

test = con.execute("""
    SELECT *
    FROM read_csv(
        'train_source2.tsv',
        delim='\t',
        header=true,
        union_by_name=true
    )
    LIMIT 5
""").df()

display(test)

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [50]:
s2_count = con.execute("""
    SELECT COUNT(*)
    FROM read_csv(
        'train_source2.tsv',
        delim='\t',
        header=true
    )
""").fetchone()[0]

s3_count = con.execute("""
    SELECT COUNT(*)
    FROM read_csv(
        'train_source3.tsv',
        delim='\t',
        header=true
    )
""").fetchone()[0]

print("S2 rows:", s2_count)
print("S3 rows:", s3_count)

S2 rows: 5034616
S3 rows: 5285603

In [51]:
# Create small lookup tables from our 100 S1 records

name_lookup_rows = []
exact_lookup_rows = []
address_lookup_rows = []

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    # -------------------------
    # Exact normalized name
    # -------------------------
    exact_name = normalize_text(row["business_name"])

    if exact_name:
        exact_lookup_rows.append({
            "s1_id": s1_id,
            "country": country,
            "exact_name": exact_name
        })

    # -------------------------
    # Name prefix keys
    # -------------------------
    for prefix in set(row["name_prefixes"]):
        name_lookup_rows.append({
            "s1_id": s1_id,
            "country": country,
            "prefix": prefix
        })

    # -------------------------
    # Address number + prefix
    # -------------------------
    numbers = set(row["address_numbers"])
    prefixes = set(row["address_prefixes"])

    for number in numbers:
        for prefix in prefixes:
            address_lookup_rows.append({
                "s1_id": s1_id,
                "country": country,
                "number": str(number),
                "prefix": prefix
            })


name_lookup_df = pd.DataFrame(name_lookup_rows)
exact_lookup_df = pd.DataFrame(exact_lookup_rows)
address_lookup_df = pd.DataFrame(address_lookup_rows)

con.register("name_lookup", name_lookup_df)
con.register("exact_lookup", exact_lookup_df)
con.register("address_lookup", address_lookup_df)

print("Lookup tables ready ✅")
print("Name keys:", len(name_lookup_df))
print("Exact-name keys:", len(exact_lookup_df))
print("Address keys:", len(address_lookup_df))

Lookup tables ready ✅
Name keys: 226
Exact-name keys: 100
Address keys: 994

In [52]:
con.execute("""
PRAGMA threads=4;

CREATE OR REPLACE TEMP TABLE blocking_candidates AS

WITH source_data AS (

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean,
        lower(
            regexp_replace(
                coalesce(business_address, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS address_clean

    FROM read_csv(
        'train_source2.tsv',
        delim='\\t',
        header=true,
        auto_detect=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean,
        lower(
            regexp_replace(
                coalesce(business_address, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS address_clean

    FROM read_csv(
        'train_source3.tsv',
        delim='\\t',
        header=true,
        auto_detect=true
    )
),

-- -------------------------
-- Exact normalized name
-- -------------------------

exact_matches AS (

    SELECT DISTINCT
        e.s1_id,
        s.entity_id AS candidate_id

    FROM source_data s

    JOIN exact_lookup e
      ON s.country = e.country
     AND s.name_clean = e.exact_name

    WHERE s.name_clean <> ''
),

-- -------------------------
-- Name token prefixes
-- -------------------------

source_name_tokens AS (

    SELECT
        s.entity_id,
        s.country,
        substr(trim(token), 1, 4) AS prefix

    FROM source_data s,
    UNNEST(string_split(s.name_clean, ' ')) AS u(token)

    WHERE length(trim(token)) >= 3
      AND lower(trim(token)) NOT IN (
          'inc', 'incorporated',
          'ltd', 'limited',
          'llc', 'pllc',
          'corp', 'corporation',
          'co', 'company',
          'pvt', 'private',
          'public', 'plc'
      )
),

name_matches AS (

    SELECT
        l.s1_id,
        t.entity_id AS candidate_id

    FROM source_name_tokens t

    JOIN name_lookup l
      ON t.country = l.country
     AND t.prefix = l.prefix

    GROUP BY
        l.s1_id,
        t.entity_id

    HAVING COUNT(DISTINCT t.prefix) >= 2
),

-- -------------------------
-- Address numbers
-- -------------------------

source_address_numbers AS (

    SELECT
        s.entity_id,
        s.country,
        number

    FROM source_data s,
    UNNEST(
        regexp_extract_all(s.address_clean, '\\d+')
    ) AS u(number)

    WHERE number <> ''
),

-- -------------------------
-- Address token prefixes
-- -------------------------

source_address_tokens AS (

    SELECT
        s.entity_id,
        s.country,
        substr(trim(token), 1, 4) AS prefix

    FROM source_data s,
    UNNEST(string_split(s.address_clean, ' ')) AS u(token)

    WHERE length(trim(token)) >= 4
),

address_matches AS (

    SELECT DISTINCT
        l.s1_id,
        n.entity_id AS candidate_id

    FROM source_address_numbers n

    JOIN source_address_tokens a
      ON n.entity_id = a.entity_id
     AND n.country = a.country

    JOIN address_lookup l
      ON n.country = l.country
     AND n.number = l.number
     AND a.prefix = l.prefix
)

-- -------------------------
-- UNION all blocking passes
-- -------------------------

SELECT DISTINCT s1_id, candidate_id
FROM exact_matches

UNION

SELECT DISTINCT s1_id, candidate_id
FROM name_matches

UNION

SELECT DISTINCT s1_id, candidate_id
FROM address_matches
""").fetchdf()

print("✅ Blocking candidates created")

✅ Blocking candidates created

In [53]:
# -----------------------------------------
# Evaluate DuckDB blocking candidates
# -----------------------------------------

candidate_df = con.execute("""
    SELECT s1_id, candidate_id
    FROM blocking_candidates
""").fetchdf()

print("Total candidate pairs:", len(candidate_df))

# Convert candidates into:
# S1 -> set of candidate IDs
candidates_by_s1 = defaultdict(set)

for s1_id, candidate_id in zip(
    candidate_df["s1_id"],
    candidate_df["candidate_id"]
):
    candidates_by_s1[s1_id].add(candidate_id)


# -----------------------------------------
# Compare with Ground Truth
# -----------------------------------------

evaluation = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]

    if row["matched_entity_ids"] == "":
        true_matches = set()
    else:
        true_matches = set(
            row["matched_entity_ids"].split(",")
        )

    candidates = candidates_by_s1.get(
        s1_id,
        set()
    )

    found = true_matches.intersection(candidates)

    missed = true_matches - candidates

    recall = (
        len(found) / len(true_matches)
        if len(true_matches) > 0
        else None
    )

    evaluation.append({
        "s1_id": s1_id,
        "true_matches": len(true_matches),
        "candidates": len(candidates),
        "found": len(found),
        "missed": len(missed),
        "recall": recall
    })


blocking_eval = pd.DataFrame(evaluation)

# -----------------------------------------
# Summary
# -----------------------------------------

non_singletons = blocking_eval[
    blocking_eval["true_matches"] > 0
]

singletons = blocking_eval[
    blocking_eval["true_matches"] == 0
]

print("\n========== BLOCKING RESULTS ==========")

print("S1 tested:", len(blocking_eval))

print(
    "Overall blocking recall:",
    round(
        non_singletons["found"].sum()
        / non_singletons["true_matches"].sum(),
        4
    )
)

print(
    "Average candidates per S1:",
    round(
        blocking_eval["candidates"].mean(),
        2
    )
)

print(
    "Median candidates per S1:",
    round(
        blocking_eval["candidates"].median(),
        2
    )
)

print(
    "Maximum candidates:",
    blocking_eval["candidates"].max()
)

print(
    "\nSingleton S1s:",
    len(singletons)
)

print(
    "Singletons with candidates:",
    (singletons["candidates"] > 0).sum()
)

print("\nWorst 10 S1s:")
display(
    blocking_eval
    .sort_values(
        ["recall", "candidates"],
        na_position="first"
    )
    .head(10)
)

Total candidate pairs: 3454082

========== BLOCKING RESULTS ==========
S1 tested: 100
Overall blocking recall: 0.9455
Average candidates per S1: 34540.82
Median candidates per S1: 2741.5
Maximum candidates: 288204

Singleton S1s: 12
Singletons with candidates: 12

Worst 10 S1s:

           s1_id  true_matches  candidates  found  missed  recall
2   S1-949002960             0         214      0       0     NaN
72  S1-159871837             0         298      0       0     NaN
63  S1-925859038             0         631      0       0     NaN
30  S1-650696290             0         661      0       0     NaN
99  S1-544555328             0        1087      0       0     NaN
1   S1-541260963             0        1126      0       0     NaN
93  S1-391683240             0        4262      0       0     NaN
16  S1-447199310             0        4900      0       0     NaN
79  S1-752379599             0        6878      0       0     NaN
89  S1-818320211             0       19739      0       0     NaN

In [54]:
# Find non-singleton S1s where our blocker missed true matches

missed_rows = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]

    if row["matched_entity_ids"] == "":
        continue

    true_ids = set(row["matched_entity_ids"].split(","))

    candidate_ids = candidates_by_s1.get(s1_id, set())

    missed = true_ids - candidate_ids

    if missed:
        missed_rows.append({
            "s1_id": s1_id,
            "true_matches": len(true_ids),
            "found": len(true_ids & candidate_ids),
            "missed": len(missed),
            "missed_ids": ",".join(sorted(missed))
        })

missed_df = pd.DataFrame(missed_rows)

print("S1s with missed true matches:", len(missed_df))

display(
    missed_df.sort_values(
        "missed",
        ascending=False
    ).head(10)
)

S1s with missed true matches: 12

,s1_id,true_matches,found,missed,missed_ids
11,S1-867998778,4,1,3,"S2-126598464,S2-648058432,S3-807085228"
10,S1-193618187,4,1,3,"S2-641725400,S3-106454164,S3-942460482"
1,S1-128350097,7,5,2,"S2-121897499,S2-268413508"
2,S1-757078074,3,1,2,"S2-308074507,S2-765988822"
3,S1-174146241,4,3,1,S2-906926745
0,S1-983540069,6,5,1,S2-4190133
4,S1-589302928,3,2,1,S3-621332247
5,S1-320151505,3,2,1,S2-230628758
7,S1-876916368,2,1,1,S3-877739558
6,S1-694830809,5,4,1,S3-156666432

In [55]:
# ------------------------------------------------
# Get the actual records for missed true matches
# ------------------------------------------------

# Collect all missed S2/S3 IDs
missed_ids = set()

for ids in missed_df["missed_ids"]:
    if ids:
        missed_ids.update(ids.split(","))

# Get the S1 records
missed_s1_ids = set(missed_df["s1_id"])

missed_s1_records = train_s1[
    train_s1["entity_id"].isin(missed_s1_ids)
].copy()

# Register missed target IDs with DuckDB
missed_id_df = pd.DataFrame({
    "entity_id": list(missed_ids)
})

con.register("missed_id_lookup", missed_id_df)

# Get missed S2 records
missed_s2 = con.execute("""
    SELECT
        s.entity_id,
        s.business_name,
        s.business_address,
        s.country
    FROM read_csv(
        'train_source2.tsv',
        delim='\t',
        header=true
    ) s
    INNER JOIN missed_id_lookup m
        ON s.entity_id = m.entity_id
""").fetchdf()

# Get missed S3 records
missed_s3 = con.execute("""
    SELECT
        s.entity_id,
        s.business_name,
        s.business_address,
        s.country
    FROM read_csv(
        'train_source3.tsv',
        delim='\t',
        header=true
    ) s
    INNER JOIN missed_id_lookup m
        ON s.entity_id = m.entity_id
""").fetchdf()

print("Missed S2 records:", len(missed_s2))
print("Missed S3 records:", len(missed_s3))

print("\nMISSED S2 RECORDS")
display(missed_s2)

print("\nMISSED S3 RECORDS")
display(missed_s3)

Missed S2 records: 11
Missed S3 records: 7

MISSED S2 RECORDS

,entity_id,business_name,business_address,country
0,S2-308074507,SA ERRGIDE ERRGIDE INC.,NaN,US
1,S2-230628758,fetechnationaltwin.com,"WOODBURN ROAD, MILAN, IN",US
2,S2-906926745,frontierpatriotmolecular.com,"0240 CEDAR LANE, KNOXVILLE, AR",US
3,S2-765988822,SA Enbridge,"CARRIAGE DALE CT, SPRING TOWNSHIIP, TX",US
4,S2-641725400,YWH LLC Center,NaN,US
5,S2-4190133,एसएस टेक्नोलॉजी प्राइवेट लिमिटेड,"SHOP NO. 01164, DELHI, CENTRAL DELHI, Delhi",India
6,S2-126598464,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"ERNAKULAM, Kerala, HOUSE, ERNAKULAM, N/A",India
7,S2-268413508,"FU, EMMERT ÁND","1708 MOUNT HOOD STREET, THE DALLES, OR",US
8,S2-121897499,fuemmertperkins.com,"1708 MOUNT HOOD STREET, THE DALLES, OR",US
9,S2-648058432,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"HOUSE, N/A, ERNAKULAM, Kerala",India
10,S2-461454382,AH Agro Private,NaN,India

MISSED S3 RECORDS

,entity_id,business_name,business_address,country
0,S3-156666432,Solonyx,"House No. 00253 Block Road Ekma, Ekma, Saran, BR",India
1,S3-807085228,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"House, Ernakulam, Kerala, Keralam",India
2,S3-106454164,YWH Convnrtisdle LLC LLC,"06220 Harvest St, Ohio, Springfield",US
3,S3-877739558,Canitfal Group P.C.,"Kentucky, 993 Willow Springs Dr, Lyndon",US
4,S3-621332247,Munoz and Kagouhman Inc,"Hancock St, Richmond City, Virginia",US
5,S3-830195342,signaturenutritiongroup.com,"2351 Presbury St, Baltimore, Maryland",US
6,S3-942460482,Llc YWH Convertible,"06220 Harvest Street, Springfield, Ohio",US

In [56]:
# -----------------------------------------
# Show S1 + its missed true S2/S3 records
# -----------------------------------------

missed_pairs = []

# Create quick lookup for missed S2/S3 records
all_missed_records = pd.concat(
    [missed_s2, missed_s3],
    ignore_index=True
)

record_lookup = {
    row["entity_id"]: row
    for _, row in all_missed_records.iterrows()
}

s1_lookup = {
    row["entity_id"]: row
    for _, row in train_s1.iterrows()
}

for _, row in missed_df.iterrows():

    s1_id = row["s1_id"]

    s1_row = s1_lookup[s1_id]

    for missed_id in row["missed_ids"].split(","):

        candidate = record_lookup.get(missed_id)

        if candidate is not None:

            missed_pairs.append({
                "s1_id": s1_id,
                "s1_name": s1_row["business_name"],
                "s1_address": s1_row["business_address"],
                "candidate_id": missed_id,
                "candidate_name": candidate["business_name"],
                "candidate_address": candidate["business_address"]
            })

missed_pairs_df = pd.DataFrame(missed_pairs)

print("Total missed true pairs:", len(missed_pairs_df))

display(
    missed_pairs_df.head(20)
)

Total missed true pairs: 18

,s1_id,s1_name,s1_address,candidate_id,candidate_name,candidate_address
0,S1-983540069,Ss Technology Private Limited,"Shop No. 1164, Pvt No.2, First Floor Kucha Mah...",S2-4190133,एसएस टेक्नोलॉजी प्राइवेट लिमिटेड,"SHOP NO. 01164, DELHI, CENTRAL DELHI, Delhi"
1,S1-128350097,"Fu, Emmert & Perkins Oaktree","1710 Mount Hood Street, The Dalles, OR",S2-121897499,fuemmertperkins.com,"1708 MOUNT HOOD STREET, THE DALLES, OR"
2,S1-128350097,"Fu, Emmert & Perkins Oaktree","1710 Mount Hood Street, The Dalles, OR",S2-268413508,"FU, EMMERT ÁND","1708 MOUNT HOOD STREET, THE DALLES, OR"
3,S1-757078074,SA Enbridge Inc.,"17119 Carriage Dale Court, Spring, TX",S2-308074507,SA ERRGIDE ERRGIDE INC.,NaN
4,S1-757078074,SA Enbridge Inc.,"17119 Carriage Dale Court, Spring, TX",S2-765988822,SA Enbridge,"CARRIAGE DALE CT, SPRING TOWNSHIIP, TX"
5,S1-174146241,Frontier Patriot Molecular Inc,"240 Cedar Lane, Clarksville, AR",S2-906926745,frontierpatriotmolecular.com,"0240 CEDAR LANE, KNOXVILLE, AR"
6,S1-589302928,Munoz & Kaufman Inc,"408 Hancock Street, Richmond City, VA",S3-621332247,Munoz and Kagouhman Inc,"Hancock St, Richmond City, Virginia"
7,S1-320151505,Fetech National Twin,"19034 Woodburn Road, Woodburn, IN",S2-230628758,fetechnationaltwin.com,"WOODBURN ROAD, MILAN, IN"
8,S1-694830809,Saran India Private Limited,"House No. 253 Block Road Ekma, Ekma, Saran, Bihar",S3-156666432,Solonyx,"House No. 00253 Block Road Ekma, Ekma, Saran, BR"
9,S1-876916368,Capital Group P.C.,"927 Willow Springs Dr, Lyndon, KY",S3-877739558,Canitfal Group P.C.,"Kentucky, 993 Willow Springs Dr, Lyndon"
10,S1-632088756,AH Agro Private Limited,"Site No. 4, Golden Industrial Layout Kaniyur V...",S2-461454382,AH Agro Private,NaN
11,S1-313448121,Signature Nutrition Group,"2006 Presbury Street, Baltimore, MD",S3-830195342,signaturenutritiongroup.com,"2351 Presbury St, Baltimore, Maryland"
12,S1-193618187,YWH Convertible LLC,"6220 Harvest Street, Springfield, OH",S2-641725400,YWH LLC Center,NaN
13,S1-193618187,YWH Convertible LLC,"6220 Harvest Street, Springfield, OH",S3-106454164,YWH Convnrtisdle LLC LLC,"06220 Harvest St, Ohio, Springfield"
14,S1-193618187,YWH Convertible LLC,"6220 Harvest Street, Springfield, OH",S3-942460482,Llc YWH Convertible,"06220 Harvest Street, Springfield, Ohio"
15,S1-867998778,Premier Sunrise International Private Limited,"House, 40/445, Mamangalam, Palarivattom P.O, E...",S2-126598464,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"ERNAKULAM, Kerala, HOUSE, ERNAKULAM, N/A"
16,S1-867998778,Premier Sunrise International Private Limited,"House, 40/445, Mamangalam, Palarivattom P.O, E...",S2-648058432,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"HOUSE, N/A, ERNAKULAM, Kerala"
17,S1-867998778,Premier Sunrise International Private Limited,"House, 40/445, Mamangalam, Palarivattom P.O, E...",S3-807085228,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"House, Ernakulam, Kerala, Keralam"

In [57]:
# ==========================================
# IMPROVED BLOCKING V2
# ==========================================

# New candidates will be added to existing
# fast_candidates / blocking_candidates

improved_candidates = defaultdict(set)

# ------------------------------------------
# Build lookup tables for 100 S1
# ------------------------------------------

compact_name_lookup = defaultdict(set)
short_token_lookup = defaultdict(set)
address_token_pair_lookup = defaultdict(set)
address_number_lookup = defaultdict(set)

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    # ======================================
    # 1. COMPACT NAME PREFIX
    # ======================================
    name = normalize_text(row["business_name"])

    # remove spaces -> useful for:
    # ABC Corporation -> abccorporation
    # abc.com -> abccom
    compact = re.sub(r"[^a-z0-9]", "", name.lower())

    if len(compact) >= 6:
        key = compact[:8]
        compact_name_lookup[(country, key)].add(s1_id)

    # ======================================
    # 2. SHORT / FIRST TOKEN BLOCK
    # ======================================
    tokens = name.split()

    for token in tokens:

        # normal 3+ character informative tokens
        if len(token) >= 3 and token not in LEGAL_SUFFIXES:

            short_key = token[:3]

            short_token_lookup[
                (country, short_key)
            ].add(s1_id)

        # 2-character tokens
        # only keep if not a legal/common word
        elif len(token) == 2 and token.isalpha():

            short_token_lookup[
                (country, token)
            ].add(s1_id)

    # ======================================
    # 3. ADDRESS TOKEN PAIRS
    # ======================================
    addr = normalize_text(row["business_address"])

    addr_tokens = [
        t[:4]
        for t in addr.split()
        if len(t) >= 4
    ]

    addr_tokens = sorted(set(addr_tokens))

    for pair in combinations(addr_tokens, 2):

        address_token_pair_lookup[
            (country, pair)
        ].add(s1_id)

    # ======================================
    # 4. NORMALIZED ADDRESS NUMBERS
    # ======================================
    numbers = re.findall(r"\d+", addr)

    for number in numbers:

        # remove leading zeros
        normalized_number = number.lstrip("0")

        if normalized_number == "":
            normalized_number = "0"

        address_number_lookup[
            (country, normalized_number)
        ].add(s1_id)


print("New blocking lookups ready ✅")

print("Compact-name keys:",
      len(compact_name_lookup))

print("Short-token keys:",
      len(short_token_lookup))

print("Address-token-pair keys:",
      len(address_token_pair_lookup))

print("Address-number keys:",
      len(address_number_lookup))

New blocking lookups ready ✅
Compact-name keys: 100
Short-token keys: 200
Address-token-pair keys: 1586
Address-number keys: 126

In [58]:
# ==========================================
# CHECK FREQUENCY OF OUR CURRENT BLOCKING KEYS
# ==========================================

# -----------------------------
# 1. Short-name keys
# -----------------------------

short_key_rows = []

for (country, key), s1_ids in short_token_lookup.items():
    short_key_rows.append({
        "country": country,
        "key": key
    })

short_key_df = pd.DataFrame(short_key_rows).drop_duplicates()


# -----------------------------
# 2. Address token-pair keys
# -----------------------------

address_key_rows = []

for (country, pair), s1_ids in address_token_pair_lookup.items():

    address_key_rows.append({
        "country": country,
        "prefix1": pair[0],
        "prefix2": pair[1]
    })

address_key_df = pd.DataFrame(address_key_rows).drop_duplicates()


con.register("short_key_lookup", short_key_df)
con.register("address_key_lookup", address_key_df)

print("Short keys:", len(short_key_df))
print("Address-pair keys:", len(address_key_df))


# ==========================================
# SHORT NAME TOKEN FREQUENCY
# ==========================================

short_freq = con.execute("""
WITH source_data AS (

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source2.tsv',
        delim='\\t',
        header=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source3.tsv',
        delim='\\t',
        header=true
    )
),

tokens AS (

    SELECT DISTINCT
        entity_id,
        country,

        CASE
            WHEN length(trim(token)) = 2
            THEN lower(trim(token))
            ELSE substr(lower(trim(token)), 1, 3)
        END AS key

    FROM source_data,
    UNNEST(string_split(name_clean, ' '))
    AS t(token)

    WHERE length(trim(token)) >= 2
)

SELECT
    l.country,
    l.key,
    COUNT(DISTINCT t.entity_id) AS record_count

FROM short_key_lookup l

LEFT JOIN tokens t
    ON t.country = l.country
   AND t.key = l.key

GROUP BY
    l.country,
    l.key

ORDER BY record_count DESC
""").fetchdf()


print("\n===== SHORT TOKEN FREQUENCY =====")
display(short_freq.head(20))

Short keys: 200
Address-pair keys: 1586

===== SHORT TOKEN FREQUENCY =====

   country  key  record_count
0       US  com        389752
1    India  ind        340715
2       US  cen        316587
3       US  par        290148
4       US  and        251103
5       US  car        239009
6       US  ser        232646
7       US  gro        217843
8    India  ser        209440
9       US  ass        184583
10      US   of        150888
11   India  con        149898
12      US  hea        144649
13   India  tra        139449
14   India  llp        139146
15   India  inf        135989
16      US  int        130606
17   India  tec        128948
18   India  pro        122005
19      US  con        111279

In [59]:
display(short_freq.head(20))

   country  key  record_count
0       US  com        389752
1    India  ind        340715
2       US  cen        316587
3       US  par        290148
4       US  and        251103
5       US  car        239009
6       US  ser        232646
7       US  gro        217843
8    India  ser        209440
9       US  ass        184583
10      US   of        150888
11   India  con        149898
12      US  hea        144649
13   India  tra        139449
14   India  llp        139146
15   India  inf        135989
16      US  int        130606
17   India  tec        128948
18   India  pro        122005
19      US  con        111279

In [60]:
# ==========================================
# Identify useful short blocking keys
# ==========================================

MAX_SHORT_FREQ = 1000

# Keep short keys that occur in <= 1000 records
useful_short = short_freq[
    short_freq["record_count"] <= MAX_SHORT_FREQ
].copy()

print("Total short keys:", len(short_freq))
print("Useful short keys:", len(useful_short))

print("\nUseful short keys:")
display(
    useful_short
    .sort_values("record_count")
    .head(30)
)

Total short keys: 200
Useful short keys: 20

Useful short keys:

    country  key  record_count
199      US  ywh             8
198   India  ois            19
197   India  roz            42
196   India  ayr            66
195   India  rrs           135
194   India   oq           152
193   India   fx           239
192   India   dv           278
191      US   sa           282
190   India   ah           285
189      US   fu           291
188      US  goa           339
187   India  hex           344
186   India  ree           528
185      US  reu           534
184      US  keo           604
183      US  did           649
182      US  fet           687
181   India   ks           702
180   India  til           850

In [61]:
# Which of our S1 blocking keys are actually useful?

s1_short_keys = set()

for _, row in sample_100_s1.iterrows():

    country = row["country"]

    for key in row["name_prefixes"]:
        s1_short_keys.add((country, key[:3]))

useful_s1_keys = []

for country, key in s1_short_keys:

    match = useful_short[
        (useful_short["country"] == country) &
        (useful_short["key"] == key)
    ]

    if not match.empty:
        useful_s1_keys.append(
            (country, key)
        )

print("Total S1 short keys:", len(s1_short_keys))
print("Useful S1 short keys:", len(useful_s1_keys))

print("\nExamples:")
print(useful_s1_keys[:30])

Total S1 short keys: 180
Useful S1 short keys: 9

Examples:
[('US', 'goa'), ('India', 'ree'), ('US', 'did'), ('US', 'fet'), ('US', 'keo'), ('India', 'roz'), ('US', 'reu'), ('India', 'til'), ('India', 'ayr')]

In [62]:
print("Useful short keys:")

display(
    useful_short[
        ["country", "key", "record_count"]
    ].sort_values("record_count")
)

Useful short keys:

    country  key  record_count
199      US  ywh             8
198   India  ois            19
197   India  roz            42
196   India  ayr            66
195   India  rrs           135
194   India   oq           152
193   India   fx           239
192   India   dv           278
191      US   sa           282
190   India   ah           285
189      US   fu           291
188      US  goa           339
187   India  hex           344
186   India  ree           528
185      US  reu           534
184      US  keo           604
183      US  did           649
182      US  fet           687
181   India   ks           702
180   India  til           850

In [63]:
# Useful short-token lookup

useful_short_lookup = defaultdict(set)

for _, row in useful_short.iterrows():
    useful_short_lookup[
        (row["country"], row["key"])
    ].add(row["key"])

print("Useful short-token lookup created ✅")
print("Number of useful keys:", len(useful_short_lookup))

Useful short-token lookup created ✅
Number of useful keys: 20

In [64]:
# See which useful short keys belong to our 100 S1s

useful_s1_short_keys = []

for _, row in sample_100_s1.iterrows():

    country = row["country"]

    for prefix in row["name_prefixes"]:

        key = prefix[:3]

        if (country, key) in useful_short_lookup:
            useful_s1_short_keys.append(
                (row["entity_id"], country, key)
            )

useful_s1_short_keys = pd.DataFrame(
    useful_s1_short_keys,
    columns=["s1_id", "country", "key"]
).drop_duplicates()

print("Useful S1-key pairs:",
      len(useful_s1_short_keys))

display(useful_s1_short_keys.head(20))

Useful S1-key pairs: 9

          s1_id country  key
0  S1-320151505      US  fet
1  S1-169338169      US  reu
2  S1-802535179      US  goa
3  S1-818320211   India  roz
4  S1-857232066   India  ayr
5  S1-207329319      US  did
6  S1-803297813      US  keo
7  S1-745738595   India  til
8  S1-154182001   India  ree

In [65]:
# ==========================================
# 4-CHARACTER NAME KEY FREQUENCY
# ==========================================

name4_rows = []

for _, row in sample_100_s1.iterrows():

    country = row["country"]

    for prefix in set(row["name_prefixes"]):

        # Only 4+ character prefixes
        if len(prefix) >= 4:
            name4_rows.append({
                "country": country,
                "key": prefix[:4]
            })

name4_lookup_df = pd.DataFrame(
    name4_rows
).drop_duplicates()

con.register("name4_lookup", name4_lookup_df)

print(
    "Unique 4-char S1 keys:",
    len(name4_lookup_df)
)


name4_freq = con.execute("""
WITH source_data AS (

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source2.tsv',
        delim='\t',
        header=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source3.tsv',
        delim='\t',
        header=true
    )
),

source_keys AS (

    SELECT DISTINCT
        entity_id,
        country,
        substr(lower(trim(token)), 1, 4) AS key

    FROM source_data,
    UNNEST(string_split(name_clean, ' '))
    AS t(token)

    WHERE length(trim(token)) >= 4
)

SELECT
    l.country,
    l.key,
    COUNT(DISTINCT s.entity_id) AS record_count

FROM name4_lookup l

LEFT JOIN source_keys s
    ON s.country = l.country
   AND s.key = l.key

GROUP BY
    l.country,
    l.key

ORDER BY record_count
""").fetchdf()


print("\n===== 4-CHARACTER KEY FREQUENCY =====")
display(name4_freq.head(30))

Unique 4-char S1 keys: 193

===== 4-CHARACTER KEY FREQUENCY =====

   country   key  record_count
0    India  spak            17
1    India  rozy            22
2       US  goar            29
3    India  ayra            55
4    India  reev            59
5       US  leto           112
6       US  dido           143
7       US  reus           165
8       US  rebb           166
9       US  keor           168
10      US  lass           218
11      US  fete           229
12      US  bitt           284
13      US  debe           381
14      US  shoo           382
15   India  anub           405
16      US  emme           433
17   India  coro           435
18      US  trau           445
19      US  ricc           453
20      US  ambr           519
21   India  tile           559
22   India  purp           562
23      US  some           573
24      US  gerr           714
25      US  kauf           725
26   India  sush           769
27   India  nira           800
28      US  mand           821
29      US  pera           845

In [66]:
# ==========================================
# Find useful 4-character name keys
# ==========================================

MAX_FREQ_4 = 1000

useful_4char = name4_freq[
    name4_freq["record_count"] <= MAX_FREQ_4
].copy()

print("Total 4-char keys:", len(name4_freq))
print("Useful 4-char keys:", len(useful_4char))

print("\nLeast frequent useful keys:")
display(
    useful_4char
    .sort_values("record_count")
    .head(30)
)

print("\nMost frequent useful keys:")
display(
    useful_4char
    .sort_values("record_count", ascending=False)
    .head(10)
)

Total 4-char keys: 193
Useful 4-char keys: 33

Least frequent useful keys:

   country   key  record_count
0    India  spak            17
1    India  rozy            22
2       US  goar            29
3    India  ayra            55
4    India  reev            59
5       US  leto           112
6       US  dido           143
7       US  reus           165
8       US  rebb           166
9       US  keor           168
10      US  lass           218
11      US  fete           229
12      US  bitt           284
13      US  debe           381
14      US  shoo           382
15   India  anub           405
16      US  emme           433
17   India  coro           435
18      US  trau           445
19      US  ricc           453
20      US  ambr           519
21   India  tile           559
22   India  purp           562
23      US  some           573
24      US  gerr           714
25      US  kauf           725
26   India  sush           769
27   India  nira           800
28      US  mand           821
29      US  pera           845

Most frequent useful keys:

   country   key  record_count
32      US  lyre           957
31      US  ceci           940
30   India  encl           850
29      US  pera           845
28      US  mand           821
27   India  nira           800
26   India  sush           769
25      US  kauf           725
24      US  gerr           714
23      US  some           573

In [67]:
# ==========================================
# Build lookup for useful 4-char name keys
# ==========================================

useful_4_lookup = defaultdict(set)

for _, row in useful_4char.iterrows():
    useful_4_lookup[
        (row["country"], row["key"])
    ].add(row["key"])

print("Useful 4-char keys:", len(useful_4_lookup))

Useful 4-char keys: 33

In [68]:
# ==========================================
# Build a DataFrame for useful 4-char keys
# ==========================================

useful_4_rows = []

for (country, key), _ in useful_4_lookup.items():
    useful_4_rows.append({
        "country": country,
        "key": key
    })

useful_4_df = pd.DataFrame(
    useful_4_rows
).drop_duplicates()

con.register(
    "useful_4_lookup",
    useful_4_df
)

print("Useful 4-char lookup registered ✅")
print("Number of useful 4-char keys:",
      len(useful_4_df))

display(useful_4_df)

Useful 4-char lookup registered ✅
Number of useful 4-char keys: 33

   country   key
0    India  spak
1    India  rozy
2       US  goar
3    India  ayra
4    India  reev
5       US  leto
6       US  dido
7       US  reus
8       US  rebb
9       US  keor
10      US  lass
11      US  fete
12      US  bitt
13      US  debe
14      US  shoo
15   India  anub
16      US  emme
17   India  coro
18      US  trau
19      US  ricc
20      US  ambr
21   India  tile
22   India  purp
23      US  some
24      US  gerr
25      US  kauf
26   India  sush
27   India  nira
28      US  mand
29      US  pera
30   India  encl
31      US  ceci
32      US  lyre

In [69]:
# ==========================================
# MAP USEFUL 4-CHAR KEYS TO ACTUAL S1 IDs
# ==========================================

useful_4_set = set(
    zip(
        useful_4char["country"],
        useful_4char["key"]
    )
)

rows = []

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    for prefix in set(row["name_prefixes"]):

        key = prefix[:4]

        if (country, key) in useful_4_set:

            rows.append({
                "s1_id": s1_id,
                "country": country,
                "key": key
            })

useful_4_s1_df = pd.DataFrame(rows).drop_duplicates()

con.register(
    "useful_4_s1",
    useful_4_s1_df
)

print("Useful 4-char S1-key mappings:",
      len(useful_4_s1_df))

display(useful_4_s1_df.head(20))

Useful 4-char S1-key mappings: 33

           s1_id country   key
0   S1-320151505      US  fete
1   S1-655046555      US  bitt
2   S1-169338169      US  reus
3   S1-802535179      US  goar
4   S1-642488269      US  rebb
5   S1-818320211   India  rozy
6   S1-836296604   India  coro
7   S1-216733182   India  spak
8   S1-589302928      US  kauf
9   S1-857232066   India  ayra
10  S1-207329319      US  dido
11  S1-843179540      US  ceci
12  S1-426702569   India  nira
13  S1-941261133      US  ricc
14  S1-803297813      US  keor
15  S1-398469911   India  sush
16  S1-128350097      US  emme
17  S1-650879900      US  debe
18  S1-650879900      US  mand
19  S1-330427971      US  gerr

In [70]:
# ==========================================
# GENERATE CANDIDATES USING USEFUL 4-CHAR KEYS
# ==========================================

con.execute("""
PRAGMA threads=4;

CREATE OR REPLACE TEMP TABLE useful_4_candidates AS

WITH source_data AS (

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source2.tsv',
        delim='\\t',
        header=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'train_source3.tsv',
        delim='\\t',
        header=true
    )
),

source_keys AS (

    SELECT DISTINCT
        s.entity_id,
        s.country,
        substr(
            lower(trim(u.token)),
            1,
            4
        ) AS key

    FROM source_data s,
    UNNEST(
        string_split(s.name_clean, ' ')
    ) AS u(token)

    WHERE length(trim(u.token)) >= 4

      AND lower(trim(u.token)) NOT IN (
          'inc',
          'ltd',
          'llc',
          'pllc',
          'corp',
          'company',
          'private',
          'public'
      )
)

SELECT DISTINCT
    l.s1_id,
    s.entity_id AS candidate_id

FROM source_keys s

JOIN useful_4_s1 l
  ON s.country = l.country
 AND s.key = l.key
""")

print("✅ Useful 4-char candidates generated")

✅ Useful 4-char candidates generated

In [71]:
# ==========================================
# COMBINE OLD + NEW CANDIDATES
# ==========================================

con.execute("""
CREATE OR REPLACE TEMP TABLE improved_candidates AS

SELECT DISTINCT
    s1_id,
    candidate_id
FROM blocking_candidates

UNION

SELECT DISTINCT
    s1_id,
    candidate_id
FROM useful_4_candidates
""")

result = con.execute("""
SELECT
    COUNT(*) AS total_candidate_pairs,
    COUNT(DISTINCT s1_id) AS s1_count
FROM improved_candidates
""").fetchdf()

display(result)

   total_candidate_pairs  s1_count
0                3467757       100

In [72]:
# ==========================================
# CHECK WHETHER 4-CHAR BLOCK IMPROVED RECALL
# ==========================================

# Create ground-truth pair table for our 100 S1s
gt_pairs = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if matched != "":
        for candidate_id in matched.split(","):
            gt_pairs.append({
                "s1_id": s1_id,
                "candidate_id": candidate_id
            })

gt_pairs_df = pd.DataFrame(gt_pairs)

con.register("gt_pairs_100", gt_pairs_df)

# ------------------------------------------
# Overall recall
# ------------------------------------------

recall_result = con.execute("""
SELECT
    COUNT(*) AS total_true_pairs,
    COUNT(c.candidate_id) AS captured_true_pairs,
    ROUND(
        COUNT(c.candidate_id) * 1.0 / COUNT(*),
        4
    ) AS blocking_recall
FROM gt_pairs_100 t

LEFT JOIN improved_candidates c
    ON t.s1_id = c.s1_id
   AND t.candidate_id = c.candidate_id
""").fetchdf()

display(recall_result)


# ------------------------------------------
# Candidate count per S1
# ------------------------------------------

candidate_counts = con.execute("""
SELECT
    s1_id,
    COUNT(*) AS candidates
FROM improved_candidates
GROUP BY s1_id
""").fetchdf()

# Include S1s having zero candidates
candidate_counts = sample_100_s1[
    ["entity_id"]
].rename(
    columns={"entity_id": "s1_id"}
).merge(
    candidate_counts,
    on="s1_id",
    how="left"
)

candidate_counts["candidates"] = (
    candidate_counts["candidates"]
    .fillna(0)
)

print("\nAverage candidates per S1:",
      round(candidate_counts["candidates"].mean(), 2))

print("Median candidates per S1:",
      round(candidate_counts["candidates"].median(), 2))

print("Maximum candidates:",
      int(candidate_counts["candidates"].max()))


# ------------------------------------------
# Singleton candidates
# ------------------------------------------

singleton_ids = set(
    gt_100.loc[
        gt_100["matched_entity_ids"] == "",
        "source1_entity_id"
    ]
)

singleton_counts = candidate_counts[
    candidate_counts["s1_id"].isin(singleton_ids)
]

print("\nSingleton S1s:", len(singleton_ids))

print(
    "Singletons with candidates:",
    (singleton_counts["candidates"] > 0).sum()
)

   total_true_pairs  captured_true_pairs  blocking_recall
0               330                  314           0.9515

Average candidates per S1: 34677.57
Median candidates per S1: 2741.5
Maximum candidates: 288204

Singleton S1s: 12
Singletons with candidates: 12

In [73]:
# Show the 16 true matches that are still missed

missed_true_pairs = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]

    if row["matched_entity_ids"] == "":
        continue

    true_ids = set(
        row["matched_entity_ids"].split(",")
    )

    candidate_ids = candidates_by_s1.get(
        s1_id,
        set()
    )

    missed = true_ids - candidate_ids

    for candidate_id in missed:
        missed_true_pairs.append({
            "s1_id": s1_id,
            "missed_id": candidate_id
        })

missed_true_pairs_df = pd.DataFrame(
    missed_true_pairs
)

print(
    "Remaining missed true pairs:",
    len(missed_true_pairs_df)
)

display(missed_true_pairs_df)

Remaining missed true pairs: 18

           s1_id     missed_id
0   S1-983540069    S2-4190133
1   S1-128350097  S2-268413508
2   S1-128350097  S2-121897499
3   S1-757078074  S2-765988822
4   S1-757078074  S2-308074507
5   S1-174146241  S2-906926745
6   S1-589302928  S3-621332247
7   S1-320151505  S2-230628758
8   S1-694830809  S3-156666432
9   S1-876916368  S3-877739558
10  S1-632088756  S2-461454382
11  S1-313448121  S3-830195342
12  S1-193618187  S3-106454164
13  S1-193618187  S3-942460482
14  S1-193618187  S2-641725400
15  S1-867998778  S2-648058432
16  S1-867998778  S3-807085228
17  S1-867998778  S2-126598464

In [74]:
# ==========================================
# Get missed TRUE pairs using IMPROVED blocker
# ==========================================

improved_df = con.execute("""
    SELECT s1_id, candidate_id
    FROM improved_candidates
""").fetchdf()

improved_by_s1 = defaultdict(set)

for s1_id, candidate_id in zip(
    improved_df["s1_id"],
    improved_df["candidate_id"]
):
    improved_by_s1[s1_id].add(candidate_id)


missed_true_pairs = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]

    if row["matched_entity_ids"] == "":
        continue

    true_ids = set(
        row["matched_entity_ids"].split(",")
    )

    candidate_ids = improved_by_s1.get(
        s1_id,
        set()
    )

    missed = true_ids - candidate_ids

    for candidate_id in missed:
        missed_true_pairs.append({
            "s1_id": s1_id,
            "missed_id": candidate_id
        })


missed_true_pairs_df = pd.DataFrame(
    missed_true_pairs
)

print(
    "Remaining missed true pairs:",
    len(missed_true_pairs_df)
)

display(missed_true_pairs_df)

Remaining missed true pairs: 16

           s1_id     missed_id
0   S1-983540069    S2-4190133
1   S1-128350097  S2-121897499
2   S1-757078074  S2-765988822
3   S1-757078074  S2-308074507
4   S1-174146241  S2-906926745
5   S1-589302928  S3-621332247
6   S1-694830809  S3-156666432
7   S1-876916368  S3-877739558
8   S1-632088756  S2-461454382
9   S1-313448121  S3-830195342
10  S1-193618187  S3-106454164
11  S1-193618187  S3-942460482
12  S1-193618187  S2-641725400
13  S1-867998778  S2-648058432
14  S1-867998778  S3-807085228
15  S1-867998778  S2-126598464

In [75]:
from rapidfuzz import fuzz
import re

# Combine the missed records we already found
all_missed_records = pd.concat(
    [missed_s2, missed_s3],
    ignore_index=True
)

# Make lookup: candidate_id -> record
candidate_lookup = {
    row["entity_id"]: row
    for _, row in all_missed_records.iterrows()
}

# Make lookup: S1 id -> record
s1_lookup = {
    row["entity_id"]: row
    for _, row in train_s1.iterrows()
}

analysis_rows = []

for _, pair in missed_true_pairs_df.iterrows():

    s1_id = pair["s1_id"]
    candidate_id = pair["missed_id"]

    s1_row = s1_lookup[s1_id]
    c_row = candidate_lookup[candidate_id]

    s1_name = normalize_text(s1_row["business_name"])
    c_name = normalize_text(c_row["business_name"])

    s1_addr = normalize_text(s1_row["business_address"])
    c_addr = normalize_text(c_row["business_address"])

    name_score = fuzz.token_set_ratio(
        s1_name,
        c_name
    ) / 100

    address_score = fuzz.token_set_ratio(
        s1_addr,
        c_addr
    ) / 100

    s1_numbers = set(
        re.findall(r"\d+", s1_addr)
    )

    c_numbers = set(
        re.findall(r"\d+", c_addr)
    )

    number_overlap = len(
        s1_numbers & c_numbers
    )

    analysis_rows.append({
        "s1_id": s1_id,
        "missed_id": candidate_id,
        "s1_name": s1_row["business_name"],
        "candidate_name": c_row["business_name"],
        "s1_address": s1_row["business_address"],
        "candidate_address": c_row["business_address"],
        "name_score": round(name_score, 3),
        "address_score": round(address_score, 3),
        "common_numbers": number_overlap
    })

missed_analysis = pd.DataFrame(analysis_rows)

display(missed_analysis)

,s1_id,missed_id,s1_name,candidate_name,s1_address,candidate_address,name_score,address_score,common_numbers
0,S1-983540069,S2-4190133,Ss Technology Private Limited,एसएस टेक्नोलॉजी प्राइवेट लिमिटेड,"Shop No. 1164, Pvt No.2, First Floor Kucha Mah...","SHOP NO. 01164, DELHI, CENTRAL DELHI, Delhi",0.098,0.875,0
1,S1-128350097,S2-121897499,"Fu, Emmert & Perkins Oaktree",fuemmertperkins.com,"1710 Mount Hood Street, The Dalles, OR","1708 MOUNT HOOD STREET, THE DALLES, OR",0.591,0.972,0
2,S1-757078074,S2-765988822,SA Enbridge Inc.,SA Enbridge,"17119 Carriage Dale Court, Spring, TX","CARRIAGE DALE CT, SPRING TOWNSHIIP, TX",1.000,0.793,0
3,S1-757078074,S2-308074507,SA Enbridge Inc.,SA ERRGIDE ERRGIDE INC.,"17119 Carriage Dale Court, Spring, TX",NaN,0.828,0.000,0
4,S1-174146241,S2-906926745,Frontier Patriot Molecular Inc,frontierpatriotmolecular.com,"240 Cedar Lane, Clarksville, AR","0240 CEDAR LANE, KNOXVILLE, AR",0.621,0.842,0
5,S1-589302928,S3-621332247,Munoz & Kaufman Inc,Munoz and Kagouhman Inc,"408 Hancock Street, Richmond City, VA","Hancock St, Richmond City, Virginia",0.800,0.794,0
6,S1-694830809,S3-156666432,Saran India Private Limited,Solonyx,"House No. 253 Block Road Ekma, Ekma, Saran, Bihar","House No. 00253 Block Road Ekma, Ekma, Saran, BR",0.118,0.937,0
7,S1-876916368,S3-877739558,Capital Group P.C.,Canitfal Group P.C.,"927 Willow Springs Dr, Lyndon, KY","Kentucky, 993 Willow Springs Dr, Lyndon",0.914,0.873,0
8,S1-632088756,S2-461454382,AH Agro Private Limited,AH Agro Private,"Site No. 4, Golden Industrial Layout Kaniyur V...",NaN,1.000,0.000,0
9,S1-313448121,S3-830195342,Signature Nutrition Group,signaturenutritiongroup.com,"2006 Presbury Street, Baltimore, MD","2351 Presbury St, Baltimore, Maryland",0.500,0.765,0
10,S1-193618187,S3-106454164,YWH Convertible LLC,YWH Convnrtisdle LLC LLC,"6220 Harvest Street, Springfield, OH","06220 Harvest St, Ohio, Springfield",0.872,0.896,0
11,S1-193618187,S3-942460482,YWH Convertible LLC,Llc YWH Convertible,"6220 Harvest Street, Springfield, OH","06220 Harvest Street, Springfield, Ohio",1.000,0.958,0
12,S1-193618187,S2-641725400,YWH Convertible LLC,YWH LLC Center,"6220 Harvest Street, Springfield, OH",NaN,0.727,0.000,0
13,S1-867998778,S2-648058432,Premier Sunrise International Private Limited,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"House, 40/445, Mamangalam, Palarivattom P.O, E...","HOUSE, N/A, ERNAKULAM, Kerala",0.088,0.917,0
14,S1-867998778,S3-807085228,Premier Sunrise International Private Limited,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"House, 40/445, Mamangalam, Palarivattom P.O, E...","House, Ernakulam, Kerala, Keralam",0.088,0.846,0
15,S1-867998778,S2-126598464,Premier Sunrise International Private Limited,പ്രീമിയർ സൺറൈസ് ഇന്റർനാഷണൽ പ്രൈവറ്റ് ലിമിറ്റഡ്,"House, 40/445, Mamangalam, Palarivattom P.O, E...","ERNAKULAM, Kerala, HOUSE, ERNAKULAM, N/A",0.088,0.917,0

In [76]:
# ==========================================
# ANALYZE THE 16 MISSED TRUE PAIRS
# Simple and safe version
# ==========================================

def core_name(text):
    text = normalize_text(text)

    tokens = text.split()
    cleaned = []

    for token in tokens:
        if token in LEGAL_SUFFIXES:
            continue

        if token in {"com", "www", "net", "org"}:
            continue

        cleaned.append(token)

    return "".join(cleaned)


def address_tokens(text):
    if pd.isna(text):
        return set()

    text = normalize_text(text)

    stopwords = {
        "street", "st", "road", "rd",
        "avenue", "ave", "lane", "ln",
        "drive", "dr", "court", "ct",
        "boulevard", "blvd",
        "house", "no", "number",
        "floor", "unit", "block"
    }

    result = set()

    for token in text.split():
        if len(token) >= 4 and token not in stopwords:
            result.add(token[:4])

    return result


def normalized_numbers(text):
    if pd.isna(text):
        return set()

    nums = re.findall(r"\d+", str(text))

    result = set()

    for num in nums:
        num = num.lstrip("0")

        if num == "":
            num = "0"

        result.add(num)

    return result


# Useful 3-character keys
useful_short_set = set()

for _, row in useful_short.iterrows():
    useful_short_set.add(
        (row["country"], row["key"])
    )


results = []

for _, row in missed_analysis.iterrows():

    s1_id = row["s1_id"]
    missed_id = row["missed_id"]

    country = s1_lookup[s1_id]["country"]

    s1_name = row["s1_name"]
    c_name = row["candidate_name"]

    s1_address = row["s1_address"]
    c_address = row["candidate_address"]

    # 1. Core name similarity
    s1_core = core_name(s1_name)
    c_core = core_name(c_name)

    core_match = False

    if len(s1_core) >= 8 and len(c_core) >= 8:
        if s1_core == c_core:
            core_match = True
        elif s1_core in c_core:
            core_match = True
        elif c_core in s1_core:
            core_match = True

    # 2. Rare/short token
    s1_tokens = normalize_text(s1_name).split()
    c_tokens = normalize_text(c_name).split()

    s1_short = set()
    c_short = set()

    for token in s1_tokens:
        key = token[:3]

        if (country, key) in useful_short_set:
            s1_short.add(key)

    for token in c_tokens:
        key = token[:3]

        if (country, key) in useful_short_set:
            c_short.add(key)

    short_match = bool(
        s1_short.intersection(c_short)
    )

    # 3. Address token overlap
    s1_addr = address_tokens(s1_address)
    c_addr = address_tokens(c_address)

    common_addr = s1_addr.intersection(c_addr)

    address_match = len(common_addr) >= 2

    # 4. Normalized address numbers
    s1_nums = normalized_numbers(s1_address)
    c_nums = normalized_numbers(c_address)

    number_match = bool(
        s1_nums.intersection(c_nums)
    )

    # 5. Number + address token
    strong_address = (
        number_match and
        len(common_addr) >= 1
    )

    # Final experimental capture
    captured = (
        core_match
        or short_match
        or address_match
        or number_match
        or strong_address
    )

    results.append({
        "s1_id": s1_id,
        "missed_id": missed_id,
        "core_name": core_match,
        "short_token": short_match,
        "address_tokens": address_match,
        "number_match": number_match,
        "strong_address": strong_address,
        "captured": captured
    })


better_test = pd.DataFrame(results)

display(better_test)

print(
    "\nCaptured:",
    int(better_test["captured"].sum()),
    "out of",
    len(better_test)
)

,s1_id,missed_id,core_name,short_token,address_tokens,number_match,strong_address,captured
0,S1-983540069,S2-4190133,False,False,True,True,True,True
1,S1-128350097,S2-121897499,True,False,True,False,False,True
2,S1-757078074,S2-765988822,True,True,True,False,False,True
3,S1-757078074,S2-308074507,False,True,False,False,False,True
4,S1-174146241,S2-906926745,True,False,False,True,True,True
5,S1-589302928,S3-621332247,False,False,True,False,False,True
6,S1-694830809,S3-156666432,False,False,True,True,True,True
7,S1-876916368,S3-877739558,False,False,True,False,False,True
8,S1-632088756,S2-461454382,False,True,False,False,False,True
9,S1-313448121,S3-830195342,True,False,True,False,False,True
10,S1-193618187,S3-106454164,False,True,True,True,True,True
11,S1-193618187,S3-942460482,True,True,True,True,True,True
12,S1-193618187,S2-641725400,False,True,False,False,False,True
13,S1-867998778,S2-648058432,False,False,True,False,False,True
14,S1-867998778,S3-807085228,False,False,True,False,False,True
15,S1-867998778,S2-126598464,False,False,True,False,False,True

Captured: 16 out of 16

In [77]:
print("===== RECOVERY SIGNAL COVERAGE =====")

print(
    "Core name:",
    int(better_test["core_name"].sum()),
    "of",
    len(better_test)
)

print(
    "Rare/short token:",
    int(better_test["short_token"].sum()),
    "of",
    len(better_test)
)

print(
    "Address tokens:",
    int(better_test["address_tokens"].sum()),
    "of",
    len(better_test)
)

print(
    "Normalized number:",
    int(better_test["number_match"].sum()),
    "of",
    len(better_test)
)

print(
    "Strong address:",
    int(better_test["strong_address"].sum()),
    "of",
    len(better_test)
)

===== RECOVERY SIGNAL COVERAGE =====
Core name: 5 of 16
Rare/short token: 6 of 16
Address tokens: 12 of 16
Normalized number: 5 of 16
Strong address: 5 of 16

In [78]:
# ==========================================
# TEST GENERALIZED RECOVERY RULES
# ==========================================

def compact_key(text):
    """
    Remove legal/domain suffixes and spaces.
    Keep first 8 characters.
    """
    return core_name(text)[:8]


def rare_tokens(text, country):
    tokens = normalize_text(text).split()

    result = set()

    for token in tokens:
        key = token[:3]

        if (country, key) in useful_short_set:
            result.add(key)

    return result


def addr_prefix_tokens(text):
    if pd.isna(text):
        return set()

    tokens = normalize_text(text).split()

    stopwords = {
        "street", "st", "road", "rd",
        "avenue", "ave", "lane", "ln",
        "drive", "dr", "court", "ct",
        "boulevard", "blvd",
        "house", "no", "number",
        "floor", "unit", "block",
        "building"
    }

    return {
        token[:4]
        for token in tokens
        if len(token) >= 4
        and token not in stopwords
    }


recovery_test = []

for _, row in missed_analysis.iterrows():

    s1_id = row["s1_id"]
    country = s1_lookup[s1_id]["country"]

    s1_name = row["s1_name"]
    c_name = row["candidate_name"]

    s1_address = row["s1_address"]
    c_address = row["candidate_address"]

    # -----------------------------
    # 1. Compact name
    # -----------------------------
    s1_compact = compact_key(s1_name)
    c_compact = compact_key(c_name)

    compact_match = (
        len(s1_compact) >= 6
        and len(c_compact) >= 6
        and s1_compact == c_compact
    )

    # -----------------------------
    # 2. Rare short token
    # -----------------------------
    s1_rare = rare_tokens(s1_name, country)
    c_rare = rare_tokens(c_name, country)

    rare_match = bool(
        s1_rare.intersection(c_rare)
    )

    # -----------------------------
    # 3. Two informative address tokens
    # -----------------------------
    s1_addr = addr_prefix_tokens(s1_address)
    c_addr = addr_prefix_tokens(c_address)

    common_addr = s1_addr.intersection(c_addr)

    address_pair_match = (
        len(common_addr) >= 2
    )

    # -----------------------------
    # Final recovery rule
    # -----------------------------
    captured = (
        compact_match
        or rare_match
        or address_pair_match
    )

    recovery_test.append({
        "s1_id": s1_id,
        "missed_id": row["missed_id"],
        "compact_match": compact_match,
        "rare_token_match": rare_match,
        "address_pair_match": address_pair_match,
        "captured": captured
    })


recovery_test = pd.DataFrame(recovery_test)

display(recovery_test)

print(
    "\nRecovery captured:",
    int(recovery_test["captured"].sum()),
    "out of",
    len(recovery_test)
)

,s1_id,missed_id,compact_match,rare_token_match,address_pair_match,captured
0,S1-983540069,S2-4190133,False,False,True,True
1,S1-128350097,S2-121897499,True,False,True,True
2,S1-757078074,S2-765988822,True,True,True,True
3,S1-757078074,S2-308074507,False,True,False,True
4,S1-174146241,S2-906926745,True,False,False,True
5,S1-589302928,S3-621332247,False,False,True,True
6,S1-694830809,S3-156666432,False,False,True,True
7,S1-876916368,S3-877739558,False,False,True,True
8,S1-632088756,S2-461454382,True,True,False,True
9,S1-313448121,S3-830195342,True,False,True,True
10,S1-193618187,S3-106454164,False,True,True,True
11,S1-193618187,S3-942460482,True,True,True,True
12,S1-193618187,S2-641725400,False,True,False,True
13,S1-867998778,S2-648058432,False,False,True,True
14,S1-867998778,S3-807085228,False,False,True,True
15,S1-867998778,S2-126598464,False,False,True,True

Recovery captured: 16 out of 16

In [79]:
# ==========================================
# BUILD RECOVERY LOOKUPS FOR 100 S1
# ==========================================

recovery_name_lookup = defaultdict(set)
recovery_short_lookup = defaultdict(set)
recovery_addr_pair_lookup = defaultdict(set)

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    # --------------------------------------
    # 1. COMPACT NAME LOOKUP
    # --------------------------------------

    compact = compact_key(row["business_name"])

    if len(compact) >= 8:
        recovery_name_lookup[
            (country, compact[:8])
        ].add(s1_id)

    # --------------------------------------
    # 2. RARE SHORT TOKEN LOOKUP
    # --------------------------------------

    for token in normalize_text(
        row["business_name"]
    ).split():

        key = token[:3]

        if (country, key) in useful_short_set:
            recovery_short_lookup[
                (country, key)
            ].add(s1_id)

    # --------------------------------------
    # 3. ADDRESS TOKEN-PAIR LOOKUP
    # --------------------------------------

    addr_tokens = sorted(
        addr_prefix_tokens(
            row["business_address"]
        )
    )

    for pair in combinations(addr_tokens, 2):

        recovery_addr_pair_lookup[
            (country, pair)
        ].add(s1_id)


print("Recovery lookup created ✅")

print(
    "Compact-name keys:",
    len(recovery_name_lookup)
)

print(
    "Rare-token keys:",
    len(recovery_short_lookup)
)

print(
    "Address-pair keys:",
    len(recovery_addr_pair_lookup)
)

Recovery lookup created ✅
Compact-name keys: 97
Rare-token keys: 20
Address-pair keys: 1236

In [80]:
# ==========================================
# REGISTER RECOVERY LOOKUPS IN DUCKDB
# ==========================================

# -------- Compact-name lookup --------
compact_rows = []

for (country, key), s1_ids in recovery_name_lookup.items():
    for s1_id in s1_ids:
        compact_rows.append({
            "s1_id": s1_id,
            "country": country,
            "compact_key": key
        })

compact_df = pd.DataFrame(compact_rows).drop_duplicates()


# -------- Rare-token lookup --------
short_rows = []

for (country, key), s1_ids in recovery_short_lookup.items():
    for s1_id in s1_ids:
        short_rows.append({
            "s1_id": s1_id,
            "country": country,
            "short_key": key
        })

recovery_short_df = pd.DataFrame(short_rows).drop_duplicates()


# -------- Address-pair lookup --------
addr_rows = []

for (country, pair), s1_ids in recovery_addr_pair_lookup.items():
    for s1_id in s1_ids:
        addr_rows.append({
            "s1_id": s1_id,
            "country": country,
            "addr_key1": pair[0],
            "addr_key2": pair[1]
        })

recovery_addr_df = pd.DataFrame(addr_rows).drop_duplicates()


# Register in DuckDB
con.register("recovery_compact", compact_df)
con.register("recovery_short", recovery_short_df)
con.register("recovery_addr", recovery_addr_df)

print("Recovery lookups registered ✅")

print("Compact mappings:", len(compact_df))
print("Rare-token mappings:", len(recovery_short_df))
print("Address-pair mappings:", len(recovery_addr_df))

Recovery lookups registered ✅
Compact mappings: 97
Rare-token mappings: 20
Address-pair mappings: 1290

In [81]:
# ==========================================
# ADD RECOVERY BLOCKING TO EXISTING CANDIDATES
# ==========================================

con.execute("""
CREATE OR REPLACE TEMP TABLE recovery_candidates AS

WITH source_data AS (

    SELECT
        entity_id,
        country,

        -- Clean business name
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean,

        -- Clean address
        lower(
            regexp_replace(
                coalesce(business_address, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS address_clean

    FROM read_csv(
        'train_source2.tsv',
        delim='\t',
        header=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,

        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean,

        lower(
            regexp_replace(
                coalesce(business_address, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS address_clean

    FROM read_csv(
        'train_source3.tsv',
        delim='\t',
        header=true
    )
),

source_name_keys AS (

    SELECT DISTINCT
        entity_id,
        country,

        -- first 8 chars of compact name
        substr(
            regexp_replace(name_clean, ' ', '', 'g'),
            1,
            8
        ) AS compact_key,

        -- all 3-char token keys
        substr(
            lower(trim(token)),
            1,
            3
        ) AS short_key

    FROM source_data,
    UNNEST(
        string_split(name_clean, ' ')
    ) AS t(token)

    WHERE length(trim(token)) >= 2
),

source_address_tokens AS (

    SELECT DISTINCT
        entity_id,
        country,
        substr(
            lower(trim(token)),
            1,
            4
        ) AS addr_key

    FROM source_data,
    UNNEST(
        string_split(address_clean, ' ')
    ) AS t(token)

    WHERE length(trim(token)) >= 4
),

source_address_numbers AS (

    SELECT DISTINCT
        entity_id,
        country,
        number

    FROM source_data,
    UNNEST(
        regexp_extract_all(
            address_clean,
            '\\d+'
        )
    ) AS t(number)

    WHERE number <> ''
),

-- ========================================
-- Compact name recovery
-- ========================================

compact_matches AS (

    SELECT DISTINCT
        l.s1_id,
        s.entity_id AS candidate_id

    FROM source_name_keys s

    JOIN recovery_compact l
      ON s.country = l.country
     AND s.compact_key = l.compact_key
),

-- ========================================
-- Rare token recovery
-- ========================================

short_matches AS (

    SELECT DISTINCT
        l.s1_id,
        s.entity_id AS candidate_id

    FROM source_name_keys s

    JOIN recovery_short l
      ON s.country = l.country
     AND s.short_key = l.short_key
),

-- ========================================
-- Address-pair recovery
-- ========================================

address_matches AS (

    SELECT
        l.s1_id,
        t.entity_id AS candidate_id

    FROM source_address_tokens t

    JOIN recovery_addr l
      ON t.country = l.country
     AND t.addr_key IN (
         l.addr_key1,
         l.addr_key2
     )

    GROUP BY
        l.s1_id,
        t.entity_id

    HAVING COUNT(
        DISTINCT t.addr_key
    ) >= 2
)

-- ========================================
-- Combine all recovery routes
-- ========================================

SELECT DISTINCT
    s1_id,
    candidate_id
FROM compact_matches

UNION

SELECT DISTINCT
    s1_id,
    candidate_id
FROM short_matches

UNION

SELECT DISTINCT
    s1_id,
    candidate_id
FROM address_matches
""")

print("✅ Recovery candidates created")

✅ Recovery candidates created

In [82]:
# Check recovery candidate count

recovery_count = con.execute("""
    SELECT COUNT(*)
    FROM recovery_candidates
""").fetchone()[0]

print("Recovery candidate pairs:", recovery_count)

Recovery candidate pairs: 4601761

In [83]:
# ==========================================
# CHECK WHAT RECOVERY BLOCK ACTUALLY ADDED
# ==========================================

recovery_eval = con.execute("""
SELECT
    COUNT(*) AS total_recovery_pairs,
    COUNT(DISTINCT s1_id) AS s1_count
FROM recovery_candidates
""").fetchdf()

display(recovery_eval)


# Check the 16 missed true pairs
missed_recovery = con.execute("""
SELECT
    COUNT(*) AS missed_pairs,
    COUNT(r.candidate_id) AS recovered_pairs
FROM gt_pairs_100 g

INNER JOIN (
    SELECT *
    FROM (
        SELECT DISTINCT
            s1_id,
            candidate_id
        FROM (
            SELECT * FROM recovery_candidates
        )
    )
) r
ON g.s1_id = r.s1_id
AND g.candidate_id = r.candidate_id

WHERE NOT EXISTS (
    SELECT 1
    FROM blocking_candidates b
    WHERE b.s1_id = g.s1_id
      AND b.candidate_id = g.candidate_id
)
""").fetchdf()

display(missed_recovery)

   total_recovery_pairs  s1_count
0               4601761       100

   missed_pairs  recovered_pairs
0            18               18

In [84]:
# Check how many of the 16 missed pairs
# are recovered by recovery_candidates

con.register(
    "missed_true_pairs_table",
    missed_true_pairs_df
)

check_recovery = con.execute("""
SELECT
    COUNT(*) AS total_missed,
    COUNT(r.candidate_id) AS recovered
FROM missed_true_pairs_table m

LEFT JOIN recovery_candidates r
    ON m.s1_id = r.s1_id
   AND m.missed_id = r.candidate_id
""").fetchdf()

display(check_recovery)

   total_missed  recovered
0            16         16

In [85]:
# ==========================================
# STEP 1: CREATE ML TRAINING PAIRS
# ==========================================

# Ground Truth -> positive pairs
gt_pairs = []

for _, row in gt_100.iterrows():

    s1_id = row["source1_entity_id"]
    matched = row["matched_entity_ids"]

    if pd.notna(matched) and matched != "":
        for candidate_id in matched.split(","):
            gt_pairs.append({
                "s1_id": s1_id,
                "candidate_id": candidate_id,
                "label": 1
            })

gt_pairs_100 = pd.DataFrame(gt_pairs)

con.register("gt_pairs_100", gt_pairs_100)

print("Ground-truth positive pairs:", len(gt_pairs_100))


# ------------------------------------------
# Label every blocking candidate
# ------------------------------------------

con.execute("""
CREATE OR REPLACE TEMP TABLE labeled_candidates AS

SELECT
    b.s1_id,
    b.candidate_id,

    CASE
        WHEN g.candidate_id IS NOT NULL
        THEN 1
        ELSE 0
    END AS label

FROM blocking_candidates b

LEFT JOIN gt_pairs_100 g
    ON b.s1_id = g.s1_id
   AND b.candidate_id = g.candidate_id
""")


# ------------------------------------------
# Keep all positives
# + 25 negative candidates per S1
# ------------------------------------------

con.execute("""
CREATE OR REPLACE TEMP TABLE ml_pairs AS

WITH negatives AS (

    SELECT
        s1_id,
        candidate_id,
        label,
        ROW_NUMBER() OVER (
            PARTITION BY s1_id
            ORDER BY hash(candidate_id)
        ) AS rn

    FROM labeled_candidates

    WHERE label = 0
)

SELECT
    s1_id,
    candidate_id,
    label

FROM labeled_candidates

WHERE label = 1

UNION ALL

SELECT
    s1_id,
    candidate_id,
    label

FROM negatives

WHERE rn <= 25
""")


# ------------------------------------------
# Check result
# ------------------------------------------

result = con.execute("""
SELECT
    label,
    COUNT(*) AS pair_count
FROM ml_pairs
GROUP BY label
ORDER BY label
""").fetchdf()

print("\nML pair distribution:")
display(result)

total = con.execute("""
SELECT COUNT(*) FROM ml_pairs
""").fetchone()[0]

print("Total ML pairs:", total)

Ground-truth positive pairs: 330

ML pair distribution:

   label  pair_count
0      0        2487
1      1         312

Total ML pairs: 2799

In [86]:
# ==========================================
# FETCH S1 + CANDIDATE S2/S3 RECORDS
# ==========================================

ml_pairs = con.execute("""
    SELECT
        s.s1_id,
        s.candidate_id,
        s.label,

        s1.business_name AS s1_name,
        s1.business_address AS s1_address,
        s1.country AS s1_country,

        c.business_name AS candidate_name,
        c.business_address AS candidate_address,
        c.country AS candidate_country

    FROM ml_pairs s

    INNER JOIN (
        SELECT
            entity_id,
            business_name,
            business_address,
            country
        FROM read_csv(
            'train_source1.tsv',
            delim='\t',
            header=true
        )
    ) s1
        ON s.s1_id = s1.entity_id

    INNER JOIN (
        SELECT
            entity_id,
            business_name,
            business_address,
            country

        FROM read_csv(
            'train_source2.tsv',
            delim='\t',
            header=true
        )

        UNION ALL

        SELECT
            entity_id,
            business_name,
            business_address,
            country

        FROM read_csv(
            'train_source3.tsv',
            delim='\t',
            header=true
        )
    ) c
        ON s.candidate_id = c.entity_id
""").fetchdf()

print("ML records fetched ✅")
print("Rows:", len(ml_pairs))

display(ml_pairs.head(10))

ML records fetched ✅
Rows: 2799

,s1_id,candidate_id,label,s1_name,s1_address,s1_country,candidate_name,candidate_address,candidate_country
0,S1-426953208,S2-663914190,0,Heritage Society LLC,"139 Fort Graham Road, Whitney, TX",US,Heritage Society IV,"MOORHEAD, 2015 NINTH SAINT, MN",US
1,S1-175111461,S2-311585843,0,Dermatology Medicine LLC,"1051 Van Buren Avenue, Indian Trail, NC",US,"Inc Dermatology Medicine of Irinaapolsi,","IN, 5432 TENTH ST, INDIANAPOLIS",US
2,S1-307581912,S2-372857695,0,Ambrose Commodity LLC,"63 Betsy Drive, Islip, NY",US,The Colonial Charter School Summit,"63 GREENVIEW DRIVE, AUORRA, OH",US
3,S1-709960468,S2-906159447,0,Apex Center,"4 Hillside Court, Coxsackie, NY",US,Ramirez Dominion of Huntington Incorporated,"4 ROMA LN, WEST HILLS, NY",US
4,S1-961351838,S2-62457655,0,Cascade Health Center LLC,"313 Locke Street, Woodsboro, TX",US,Conners Health Center PC,"12715D MAGGIE LN, PO BOX 3778, WILLIS, TX",US
5,S1-650879900,S2-512992290,0,Mandie Deberry Scientific Inc,"1300 Chestnut Road, Seven Hills, OH",US,spartacuscolangelomountain.com,"1300 CENTRAL AVE, SUTHERLIN, OR",US
6,S1-630149953,S2-532209531,0,Ss Construction Private Limited,"Flat No. 904, 'A' Wing, Pristine Fontana Build...",India,Grace Trading Private,"FLAT NO. 904 , BLOCK NO. 10 RAINTREE PARK, MA...",India
7,S1-836296604,S2-763547998,0,Coromandal Marketing Private Limited,"G-3, Neel Madhav, Valji Ladha Cross Road, Near...",India,KDU Strategies Pfaniivate Limited,"3C-114, NIT, NEAR DASHAHARA GROUND NEAR R K HO...",India
8,S1-174146241,S2-937892947,1,Frontier Patriot Molecular Inc,"240 Cedar Lane, Clarksville, AR",US,Frontier Patriot Molecular,"0240 CEDAR LANE, CLARKSVILLE, AR",US
9,S1-938947364,S2-578957240,0,General Design Innovations LLC,"7241 Osage Avenue, Mesa, AZ",US,Superior Talent Advisors,"NEW LONDON, MO, 7241 CAMP CREEK LN",US

In [87]:
# ==========================================
# STEP 2: FEATURE ENGINEERING
# ==========================================

from rapidfuzz import fuzz
import re
import numpy as np


def safe_text(x):
    if pd.isna(x):
        return ""
    return str(x)


def get_numbers(text):
    text = safe_text(text)

    nums = re.findall(r"\d+", text)

    # Normalize 00253 -> 253
    result = set()

    for num in nums:
        num = num.lstrip("0")

        if num == "":
            num = "0"

        result.add(num)

    return result


def token_overlap(a, b):
    a_tokens = set(normalize_text(a).split())
    b_tokens = set(normalize_text(b).split())

    if len(a_tokens) == 0 and len(b_tokens) == 0:
        return 1.0

    if len(a_tokens) == 0 or len(b_tokens) == 0:
        return 0.0

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)


def number_overlap(a, b):
    a_nums = get_numbers(a)
    b_nums = get_numbers(b)

    if len(a_nums) == 0 or len(b_nums) == 0:
        return 0.0

    return len(a_nums & b_nums) / len(a_nums | b_nums)


# ------------------------------------------
# Name features
# ------------------------------------------

ml_pairs["name_ratio"] = ml_pairs.apply(
    lambda r: fuzz.ratio(
        safe_text(r["s1_name"]),
        safe_text(r["candidate_name"])
    ) / 100,
    axis=1
)

ml_pairs["name_token_set"] = ml_pairs.apply(
    lambda r: fuzz.token_set_ratio(
        safe_text(r["s1_name"]),
        safe_text(r["candidate_name"])
    ) / 100,
    axis=1
)

ml_pairs["name_partial"] = ml_pairs.apply(
    lambda r: fuzz.partial_ratio(
        safe_text(r["s1_name"]),
        safe_text(r["candidate_name"])
    ) / 100,
    axis=1
)

ml_pairs["name_token_overlap"] = ml_pairs.apply(
    lambda r: token_overlap(
        r["s1_name"],
        r["candidate_name"]
    ),
    axis=1
)


# ------------------------------------------
# Address features
# ------------------------------------------

ml_pairs["address_ratio"] = ml_pairs.apply(
    lambda r: fuzz.ratio(
        safe_text(r["s1_address"]),
        safe_text(r["candidate_address"])
    ) / 100,
    axis=1
)

ml_pairs["address_token_set"] = ml_pairs.apply(
    lambda r: fuzz.token_set_ratio(
        safe_text(r["s1_address"]),
        safe_text(r["candidate_address"])
    ) / 100,
    axis=1
)

ml_pairs["address_partial"] = ml_pairs.apply(
    lambda r: fuzz.partial_ratio(
        safe_text(r["s1_address"]),
        safe_text(r["candidate_address"])
    ) / 100,
    axis=1
)

ml_pairs["address_token_overlap"] = ml_pairs.apply(
    lambda r: token_overlap(
        r["s1_address"],
        r["candidate_address"]
    ),
    axis=1
)

ml_pairs["number_overlap"] = ml_pairs.apply(
    lambda r: number_overlap(
        r["s1_address"],
        r["candidate_address"]
    ),
    axis=1
)


# ------------------------------------------
# Country
# ------------------------------------------

ml_pairs["country_same"] = (
    ml_pairs["s1_country"] ==
    ml_pairs["candidate_country"]
).astype(int)


# ------------------------------------------
# Missing-value features
# ------------------------------------------

ml_pairs["candidate_name_missing"] = (
    ml_pairs["candidate_name"]
    .isna()
    .astype(int)
)

ml_pairs["candidate_address_missing"] = (
    ml_pairs["candidate_address"]
    .isna()
    .astype(int)
)


print("Feature engineering complete ✅")

feature_columns = [
    "name_ratio",
    "name_token_set",
    "name_partial",
    "name_token_overlap",
    "address_ratio",
    "address_token_set",
    "address_partial",
    "address_token_overlap",
    "number_overlap",
    "country_same",
    "candidate_name_missing",
    "candidate_address_missing"
]

display(
    ml_pairs[
        ["s1_id", "candidate_id", "label"] +
        feature_columns
    ].head(10)
)

Feature engineering complete ✅

,s1_id,candidate_id,label,name_ratio,name_token_set,name_partial,name_token_overlap,address_ratio,address_token_set,address_partial,address_token_overlap,number_overlap,country_same,candidate_name_missing,candidate_address_missing
0,S1-426953208,S2-663914190,0,0.850000,0.914286,0.918919,0.500000,0.158730,0.285714,0.212766,0.000000,0.000000,1,0,0
1,S1-175111461,S2-311585843,0,0.656250,0.909091,0.875000,0.333333,0.200000,0.285714,0.285714,0.000000,0.000000,1,0,0
2,S1-307581912,S2-372857695,0,0.290909,0.363636,0.457143,0.000000,0.327273,0.327273,0.355556,0.250000,1.000000,1,0,0
3,S1-709960468,S2-906159447,0,0.185185,0.185185,0.333333,0.000000,0.321429,0.321429,0.304348,0.222222,1.000000,1,0,0
4,S1-961351838,S2-62457655,0,0.720000,0.734694,0.772727,0.333333,0.305556,0.305556,0.346154,0.083333,0.000000,1,0,0
5,S1-650879900,S2-512992290,0,0.305085,0.305085,0.340426,0.000000,0.424242,0.333333,0.392157,0.100000,1.000000,1,0,0
6,S1-630149953,S2-532209531,0,0.461538,0.500000,0.571429,0.166667,0.317308,0.271357,0.323077,0.111111,0.333333,1,0,0
7,S1-836296604,S2-763547998,0,0.550725,0.492754,0.644068,0.142857,0.267442,0.263473,0.267606,0.080000,0.500000,1,0,0
8,S1-174146241,S2-937892947,1,0.928571,1.000000,1.000000,0.750000,0.444444,0.444444,0.461538,0.666667,1.000000,1,0,0
9,S1-938947364,S2-578957240,0,0.400000,0.296296,0.440000,0.000000,0.262295,0.393443,0.355556,0.090909,1.000000,1,0,0

In [88]:
# ==========================================
# RECREATE TRAIN / VALIDATION S1 SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

all_s1_ids = sample_100_s1["entity_id"].tolist()

train_s1_ids, val_s1_ids = train_test_split(
    all_s1_ids,
    test_size=0.20,
    random_state=42
)

print("Training S1:", len(train_s1_ids))
print("Validation S1:", len(val_s1_ids))

Training S1: 80
Validation S1: 20

In [89]:
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.utils.class_weight import compute_sample_weight

train_data = ml_pairs[
    ml_pairs["s1_id"].isin(train_s1_ids)
].copy()

val_data = ml_pairs[
    ml_pairs["s1_id"].isin(val_s1_ids)
].copy()

print("Training pairs:", len(train_data))
print("Validation pairs:", len(val_data))

X_train = train_data[feature_columns]
y_train = train_data["label"]

X_val = val_data[feature_columns]
y_val = val_data["label"]

weights = compute_sample_weight(
    class_weight="balanced",
    y=y_train
)

model = HistGradientBoostingClassifier(
    max_iter=250,
    learning_rate=0.05,
    max_leaf_nodes=15,
    l2_regularization=1.0,
    random_state=42
)

model.fit(
    X_train,
    y_train,
    sample_weight=weights
)

print("✅ Model training complete")

val_prob = model.predict_proba(X_val)[:, 1]

print("First 20 probabilities:")
print(val_prob[:20])

Training pairs: 2236
Validation pairs: 563
✅ Model training complete
First 20 probabilities:
[2.67841271e-02 4.26287235e-05 1.54049038e-03 9.98017487e-01
 9.92044013e-05 7.31578750e-05 1.07428886e-04 1.21949685e-02
 1.28931027e-04 1.19024949e-04 1.25243555e-03 1.82476195e-02
 3.95808474e-05 3.95808474e-05 1.07428886e-04 1.19757357e-03
 3.95808474e-05 1.35830763e-03 4.41223873e-05 8.35316045e-05]

In [90]:
# Add model probabilities to validation data

val_data = val_data.copy()

val_data["model_prob"] = val_prob

print("model_prob column added ✅")

display(
    val_data[
        ["s1_id", "candidate_id", "label", "model_prob"]
    ].head(10)
)

model_prob column added ✅

           s1_id  candidate_id  label  model_prob
0   S1-426953208  S2-663914190      0    0.026784
4   S1-961351838   S2-62457655      0    0.000043
25  S1-434607086  S2-857336716      0    0.001540
34  S1-843179540  S2-474099966      1    0.998017
38  S1-822087158  S2-911664181      0    0.000099
39   S1-53356671  S2-597965972      0    0.000073
48  S1-822087158   S2-73780387      0    0.000107
49   S1-53356671  S2-483583998      0    0.012195
50  S1-434607086  S2-617544114      0    0.000129
53  S1-822087158  S2-728853787      0    0.000119

In [91]:
import numpy as np
import pandas as pd

def f05_score(true_set, predicted_set):

    if len(true_set) == 0:
        return 1.0 if len(predicted_set) == 0 else 0.0

    if len(predicted_set) == 0:
        return 0.0

    tp = len(true_set & predicted_set)
    fp = len(predicted_set - true_set)
    fn = len(true_set - predicted_set)

    precision = tp / (tp + fp) if (tp + fp) else 0
    recall = tp / (tp + fn) if (tp + fn) else 0

    if precision == 0 and recall == 0:
        return 0.0

    return (
        1.25 * precision * recall
    ) / (
        0.25 * precision + recall
    )


# Ground truth lookup
gt_lookup = {}

for _, row in gt_100.iterrows():

    matched = row["matched_entity_ids"]

    if pd.isna(matched) or matched == "":
        gt_lookup[row["source1_entity_id"]] = set()
    else:
        gt_lookup[row["source1_entity_id"]] = set(
            matched.split(",")
        )


threshold_results = []

for threshold in np.arange(0.50, 0.96, 0.01):

    scores = []

    for s1_id in val_s1_ids:

        rows = val_data[
            val_data["s1_id"] == s1_id
        ]

        predicted = set(
            rows.loc[
                rows["model_prob"] >= threshold,
                "candidate_id"
            ]
        )

        true_set = gt_lookup.get(
            s1_id,
            set()
        )

        score = f05_score(
            true_set,
            predicted
        )

        scores.append(score)

    threshold_results.append({
        "threshold": round(float(threshold), 2),
        "macro_F0.5": np.mean(scores)
    })


threshold_df = pd.DataFrame(threshold_results)

print("===== THRESHOLD RESULTS =====")

display(
    threshold_df.sort_values(
        "macro_F0.5",
        ascending=False
    ).head(10)
)

===== THRESHOLD RESULTS =====

    threshold  macro_F0.5
44       0.94    0.965350
45       0.95    0.946589
40       0.90    0.918475
39       0.89    0.918475
41       0.91    0.918475
42       0.92    0.918475
43       0.93    0.915350
6        0.56    0.870856
0        0.50    0.870856
1        0.51    0.870856

In [92]:
# ==========================================
# STEP 5: INSPECT VALIDATION PREDICTIONS
# ==========================================

BEST_THRESHOLD = 0.94

val_data = val_data.copy()

val_data["pred_match"] = (
    val_data["model_prob"] >= BEST_THRESHOLD
).astype(int)

print("Threshold:", BEST_THRESHOLD)

print("\nPredicted matches:",
      val_data["pred_match"].sum())

print("Actual positive labels:",
      val_data["label"].sum())

print("\nPredicted label distribution:")
print(val_data["pred_match"].value_counts())

print("\nHighest probability pairs:")

display(
    val_data[
        [
            "s1_id",
            "candidate_id",
            "label",
            "model_prob",
            "name_token_set",
            "address_token_set",
            "number_overlap",
            "country_same"
        ]
    ]
    .sort_values(
        "model_prob",
        ascending=False
    )
    .head(20)
)

Threshold: 0.94

Predicted matches: 58
Actual positive labels: 63

Predicted label distribution:
pred_match
0    505
1     58
Name: count, dtype: int64

Highest probability pairs:

,s1_id,candidate_id,label,model_prob,name_token_set,address_token_set,number_overlap,country_same
1450,S1-745738595,S3-207418140,1,0.999852,0.967742,0.963855,1.000000,1
1856,S1-937889575,S3-440743063,1,0.999849,1.000000,0.853659,1.000000,1
2363,S1-53356671,S3-996978203,1,0.999836,0.837209,0.734694,0.666667,1
1378,S1-53356671,S2-453334141,1,0.999832,0.439024,0.700000,1.000000,1
700,S1-975412735,S2-688089654,1,0.999828,0.666667,0.461538,1.000000,1
1326,S1-53356671,S2-904412198,1,0.999820,0.956522,0.700000,1.000000,1
2473,S1-983540069,S3-435171628,1,0.999818,0.945455,0.950820,0.500000,1
1139,S1-822087158,S2-420347037,1,0.999817,0.884615,0.535211,1.000000,1
730,S1-975412735,S2-160071093,1,0.999816,0.896552,0.467532,1.000000,1
296,S1-53356671,S2-256033433,1,0.999797,1.000000,0.604651,1.000000,1
200,S1-154182001,S2-247485274,1,0.999780,1.000000,0.567568,1.000000,1
320,S1-154182001,S2-230033349,1,0.999780,1.000000,0.567568,1.000000,1
1287,S1-154182001,S2-818625585,1,0.999773,0.130435,0.369863,1.000000,1
492,S1-745738595,S2-746582059,1,0.999750,1.000000,0.468900,0.666667,1
2079,S1-983540069,S3-18925596,1,0.999743,1.000000,0.833333,0.500000,1
433,S1-975412735,S2-784038194,1,0.999735,0.206897,0.461538,1.000000,1
480,S1-426702569,S2-367489307,1,0.999735,0.916667,0.402235,1.000000,1
515,S1-745738595,S2-787404353,1,0.999688,0.280702,0.487562,0.666667,1
632,S1-369198632,S2-282745196,1,0.999683,0.115385,0.478873,1.000000,1
737,S1-822087158,S2-609281890,1,0.999676,0.800000,0.535211,1.000000,1

In [93]:
# ==========================================
# CHECK VALIDATION PERFORMANCE
# ==========================================

from sklearn.metrics import confusion_matrix, precision_score, recall_score

y_true = val_data["label"]
y_pred = val_data["pred_match"]

cm = confusion_matrix(
    y_true,
    y_pred
)

print("Confusion Matrix:")
print(cm)

precision = precision_score(
    y_true,
    y_pred,
    zero_division=0
)

recall = recall_score(
    y_true,
    y_pred,
    zero_division=0
)

print("\nPrecision:", round(precision, 4))
print("Recall:", round(recall, 4))
print("Predicted matches:", int(y_pred.sum()))
print("Actual matches:", int(y_true.sum()))

Confusion Matrix:
[[499   1]
 [  6  57]]

Precision: 0.9828
Recall: 0.9048
Predicted matches: 58
Actual matches: 63

In [94]:
# ==========================================
# STEP 6: FINAL MODEL ON ALL 100 S1s
# ==========================================

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.utils.class_weight import compute_sample_weight

# Use all 2,799 labeled pairs
X_all = ml_pairs[feature_columns]
y_all = ml_pairs["label"]

# Handle class imbalance
all_weights = compute_sample_weight(
    class_weight="balanced",
    y=y_all
)

# Train final model
final_model = HistGradientBoostingClassifier(
    max_iter=250,
    learning_rate=0.05,
    max_leaf_nodes=15,
    l2_regularization=1.0,
    random_state=42
)

final_model.fit(
    X_all,
    y_all,
    sample_weight=all_weights
)

print("✅ Final model trained")
print("Training pairs:", len(ml_pairs))
print("Features:", len(feature_columns))
print("Final threshold:", 0.94)

✅ Final model trained
Training pairs: 2799
Features: 12
Final threshold: 0.94

In [95]:
# ==========================================
# STEP 7: CHECK TEST COUNTRIES
# ==========================================

print("TEST SOURCE 1 COUNTRIES")
print("--------------------------------")

test_s1_countries = con.execute("""
    SELECT
        country,
        COUNT(*) AS record_count
    FROM read_csv(
        'test_source1.tsv',
        delim='\t',
        header=true
    )
    GROUP BY country
    ORDER BY country
""").fetchdf()

display(test_s1_countries)


print("\nTEST SOURCE 2 COUNTRIES")
print("--------------------------------")

test_s2_countries = con.execute("""
    SELECT
        country,
        COUNT(*) AS record_count
    FROM read_csv(
        'test_source2.tsv',
        delim='\t',
        header=true
    )
    GROUP BY country
    ORDER BY country
""").fetchdf()

display(test_s2_countries)


print("\nTEST SOURCE 3 COUNTRIES")
print("--------------------------------")

test_s3_countries = con.execute("""
    SELECT
        country,
        COUNT(*) AS record_count
    FROM read_csv(
        'test_source3.tsv',
        delim='\t',
        header=true
    )
    GROUP BY country
    ORDER BY country
""").fetchdf()
    
display(test_s3_countries)

TEST SOURCE 1 COUNTRIES
--------------------------------

  country  record_count
0  France        259452
1   India        809986
2      US        663106

TEST SOURCE 2 COUNTRIES
--------------------------------

  country  record_count
0  France        703378
1   India       2312565
2      US       1871330

TEST SOURCE 3 COUNTRIES
--------------------------------

  country  record_count
0  France        731615
1   India       2405000
2      US       1945701

In [96]:
# ==========================================
# STEP 8: TEST 4-CHAR NAME KEY FREQUENCY
# ==========================================

con.execute("""
CREATE OR REPLACE TEMP TABLE test_name4_freq AS

WITH source_data AS (

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'test_source2.tsv',
        delim='\\t',
        header=true
    )

    UNION ALL

    SELECT
        entity_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'test_source3.tsv',
        delim='\\t',
        header=true
    )
),

tokens AS (

    SELECT DISTINCT
        entity_id,
        country,
        substr(
            lower(trim(token)),
            1,
            4
        ) AS key

    FROM source_data,
    UNNEST(
        string_split(name_clean, ' ')
    ) AS t(token)

    WHERE length(trim(token)) >= 4

      AND lower(trim(token)) NOT IN (
          'inc',
          'ltd',
          'llc',
          'pllc',
          'corp',
          'company',
          'private',
          'public',
          'com',
          'www',
          'net',
          'org'
      )
)

SELECT
    country,
    key,
    COUNT(DISTINCT entity_id) AS record_count

FROM tokens

GROUP BY
    country,
    key
""")

print("✅ Test 4-character frequency table created")

freq_summary = con.execute("""
SELECT
    country,
    COUNT(*) AS unique_keys,
    MIN(record_count) AS minimum_frequency,
    MAX(record_count) AS maximum_frequency
FROM test_name4_freq
GROUP BY country
ORDER BY country
""").fetchdf()

display(freq_summary)

✅ Test 4-character frequency table created

  country  unique_keys  minimum_frequency  maximum_frequency
0  France        42359                  1             285191
1   India       109853                  1            1427503
2      US       129623                  1             207731

In [97]:
# ==========================================
# HOW MANY TEST KEYS ARE RARE?
# ==========================================

distribution = con.execute("""
SELECT
    SUM(CASE WHEN record_count <= 10 THEN 1 ELSE 0 END) AS le_10,
    SUM(CASE WHEN record_count <= 50 THEN 1 ELSE 0 END) AS le_50,
    SUM(CASE WHEN record_count <= 100 THEN 1 ELSE 0 END) AS le_100,
    SUM(CASE WHEN record_count <= 500 THEN 1 ELSE 0 END) AS le_500,
    SUM(CASE WHEN record_count <= 1000 THEN 1 ELSE 0 END) AS le_1000,
    COUNT(*) AS total_keys
FROM test_name4_freq
""").fetchdf()

display(distribution)

      le_10     le_50    le_100    le_500   le_1000  total_keys
0  238898.0  263428.0  269862.0  277866.0  279358.0      281835

In [98]:
# ==========================================
# TEST S1: USEFUL 4-CHARACTER KEYS
# ==========================================

# Keep test keys that occur <= 100 times
MAX_TEST_KEY_FREQ = 100

useful_test_keys = con.execute("""
SELECT
    country,
    key,
    record_count
FROM test_name4_freq
WHERE record_count <= ?
ORDER BY record_count
""", [MAX_TEST_KEY_FREQ]).fetchdf()

print(
    "Useful test 4-char keys:",
    len(useful_test_keys)
)

display(
    useful_test_keys.head(30)
)

Useful test 4-char keys: 269862

   country   key  record_count
0    India  tejg             1
1    India  hiva             1
2    India  gcén             1
3    India  lodd             1
4       US  ceep             1
5    India  vgch             1
6   France  cdnf             1
7    India  hfni             1
8    India  clzb             1
9       US  edlc             1
10  France  crdo             1
11      US  easg             1
12   India  jssc             1
13      US  ewds             1
14   India  brfm             1
15      US  aiae             1
16  France  plca             1
17      US  cósb             1
18  France  mxdc             1
19  France  dico             1
20      US  vghi             1
21   India  clfm             1
22      US  eref             1
23      US  hltb             1
24   India  hmgj             1
25   India  hawo             1
26      US  irpo             1
27   India  ijce             1
28      US  rdow             1
29  France  nqcu             1

In [99]:
# ==========================================
# HOW MANY TEST S1s HAVE A RARE 4-CHAR KEY?
# ==========================================

con.execute("""
CREATE OR REPLACE TEMP TABLE test_s1_keys AS

WITH s1 AS (

    SELECT
        entity_id AS s1_id,
        country,
        lower(
            regexp_replace(
                coalesce(business_name, ''),
                '[^\\p{L}\\p{N}]+',
                ' ',
                'g'
            )
        ) AS name_clean

    FROM read_csv(
        'test_source1.tsv',
        delim='\t',
        header=true
    )
)

SELECT DISTINCT
    s1_id,
    country,
    substr(lower(trim(token)), 1, 4) AS key

FROM s1,
UNNEST(string_split(name_clean, ' ')) AS t(token)

WHERE length(trim(token)) >= 4
""")

con.register(
    "useful_test_keys",
    useful_test_keys
)

coverage = con.execute("""
SELECT
    COUNT(DISTINCT s.s1_id) AS s1_with_rare_key
FROM test_s1_keys s
JOIN useful_test_keys k
  ON s.country = k.country
 AND s.key = k.key
""").fetchdf()

display(coverage)

   s1_with_rare_key
0            137187

In [100]:
# ==========================================
# CANDIDATE SIZE OF RARE 4-CHAR KEYS
# ==========================================

rare_key_candidate_stats = con.execute("""
SELECT
    AVG(k.record_count) AS avg_candidates,
    MEDIAN(k.record_count) AS median_candidates,
    MAX(k.record_count) AS max_candidates
FROM test_s1_keys s
JOIN useful_test_keys k
  ON s.country = k.country
 AND s.key = k.key
""").fetchdf()

display(rare_key_candidate_stats)

   avg_candidates  median_candidates  max_candidates
0       47.781581               46.0             100

In [101]:
# ==========================================
# EVALUATE RARE 4-CHAR KEY ON 100 S1
# ==========================================

# Map useful 4-char keys to S1s
rare_s1_map = defaultdict(set)

for _, row in sample_100_s1.iterrows():

    s1_id = row["entity_id"]
    country = row["country"]

    for prefix in set(row["name_prefixes"]):

        key = prefix[:4]

        if (country, key) in set(
            zip(
                useful_4char["country"],
                useful_4char["key"]
            )
        ):
            rare_s1_map[s1_id].add(key)


print(
    "S1s with rare 4-char keys:",
    len(rare_s1_map)
)

S1s with rare 4-char keys: 32

In [102]:
# ==========================================
# MEASURE THE ACTUAL BENEFIT OF RARE 4-CHAR BLOCK
# ==========================================

# Total true pairs captured by rare 4-char block
rare4_result = con.execute("""
SELECT
    COUNT(*) AS true_pairs_captured_by_rare4
FROM gt_pairs_100 g
INNER JOIN useful_4_candidates r
    ON g.s1_id = r.s1_id
   AND g.candidate_id = r.candidate_id
""").fetchdf()

display(rare4_result)


# True pairs that were missed by baseline
# but recovered by rare 4-char block
newly_recovered = con.execute("""
SELECT
    COUNT(*) AS newly_recovered_true_pairs
FROM gt_pairs_100 g
INNER JOIN useful_4_candidates r
    ON g.s1_id = r.s1_id
   AND g.candidate_id = r.candidate_id
WHERE NOT EXISTS (
    SELECT 1
    FROM blocking_candidates b
    WHERE b.s1_id = g.s1_id
      AND b.candidate_id = g.candidate_id
)
""").fetchdf()

display(newly_recovered)


# How many candidate pairs did this block produce?
rare4_count = con.execute("""
SELECT COUNT(*)
FROM useful_4_candidates
""").fetchone()[0]

print(
    "Rare 4-char candidate pairs:",
    rare4_count
)

   true_pairs_captured_by_rare4
0                           103

   newly_recovered_true_pairs
0                           2

Rare 4-char candidate pairs: 14226

In [ ]:
# ==========================================
# FAST TEST SOURCE TABLE
# ==========================================

con.execute("PRAGMA threads=8")

con.execute("""
CREATE OR REPLACE TEMP TABLE test_source_fast AS

SELECT
    entity_id AS candidate_id,
    country,

    -- normalized full name
    lower(
        regexp_replace(
            coalesce(business_name, ''),
            '[^\\p{L}\\p{N}]+',
            ' ',
            'g'
        )
    ) AS name_clean,

    -- compact first 8 characters
    substr(
        regexp_replace(
            lower(coalesce(business_name, '')),
            '[^\\p{L}\\p{N}]',
            '',
            'g'
        ),
        1,
        8
    ) AS compact8,

    -- first 4 name-token prefixes
    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^([^ ]+)',
            1
        ),
        1, 4
    ) AS token1,

    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^[^ ]+ ([^ ]+)',
            1
        ),
        1, 4
    ) AS token2,

    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^[^ ]+ [^ ]+ ([^ ]+)',
            1
        ),
        1, 4
    ) AS token3

FROM read_csv(
    'test_source2.tsv',
    delim='\t',
    header=true
)

UNION ALL

SELECT
    entity_id AS candidate_id,
    country,

    lower(
        regexp_replace(
            coalesce(business_name, ''),
            '[^\\p{L}\\p{N}]+',
            ' ',
            'g'
        )
    ) AS name_clean,

    substr(
        regexp_replace(
            lower(coalesce(business_name, '')),
            '[^\\p{L}\\p{N}]',
            '',
            'g'
        ),
        1,
        8
    ) AS compact8,

    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^([^ ]+)',
            1
        ),
        1, 4
    ) AS token1,

    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^[^ ]+ ([^ ]+)',
            1
        ),
        1, 4
    ) AS token2,

    substr(
        regexp_extract(
            lower(
                regexp_replace(
                    coalesce(business_name, ''),
                    '[^\\p{L}\\p{N}]+',
                    ' ',
                    'g'
                )
            ),
            '^[^ ]+ [^ ]+ ([^ ]+)',
            1
        ),
        1, 4
    ) AS token3

FROM read_csv(
    'test_source3.tsv',
    delim='\t',
    header=true
)
""")

print("✅ Fast test source table created")